=== afaf-tech/sholawat-json/schemas/burdah_fasl_v1.1.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Burdah Fasl Schema",
    "version": "1.1",
    "type": "object",
    "properties": {
        "number": {
            "type": "integer",
            "description": "The chapter number."
        },
        "source": {
            "type": "string",
            "description": "The source of the text."
        },
        "name": {
            "type": "string",
            "description": "The Arabic name of the fasl (chapter)."
        },
        "latin": {
            "type": [
                "string",
                "null"
            ],
            "description": "The transliteration of the chapter name."
        },
        "text": {
            "type": "object",
            "description": "Contains the Arabic text and its transliteration.",
            "patternProperties": {
                "^[0-9]+$": {
                    "type": "object",
                    "properties": {
                        "arabic": {
                            "type": "string",
                            "description": "The Arabic text of the verse."
                        },
                        "latin": {
                            "type": [
                                "string",
                                "null"
                            ],
                            "description": "The transliteration of the Arabic text."
                        }
                    },
                    "required": [
                        "arabic"
                    ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "translations": {
            "type": [
                "object",
                "null"
            ],
            "description": "Translations in various languages.",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "object",
                    "description": "The key representing the language code using a two-letter ISO 639-1 code (e.g., 'en' for English, 'ar' for Arabic).",
                    "properties": {
                        "name": {
                            "type": "string",
                            "description": "The translated name of the chapter in the specified language."
                        },
                        "muqaddimah": {
                            "type": "string",
                            "description": "(introduction) of the chapter."
                        },
                        "translator": {
                            "type": "string",
                            "description": "translator of the chapter."
                        },
                        "text": {
                            "type": "object",
                            "description": "Translated text for each verse in the specified language.",
                            "patternProperties": {
                                "^[0-9]+$": {
                                    "type": "string",
                                    "description": "Translated text of the verse in the specified language."
                                }
                            },
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "name",
                        "text"
                    ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "last_updated": {
            "type": "string",
            "format": "date",
            "pattern": "^(\\d{4})-(\\d{2})-(\\d{2})$",
            "description": "The date when the data was last updated, in ISO 8601 date format (e.g., '2024-11-09')."
        }
    },
    "required": [
        "number",
        "source",
        "name",
        "last_updated"
    ],
    "anyOf": [
        {
            "required": [
                "text"
            ]
        },
        {
            "required": [
                "translations"
            ]
        }
    ],
    "additionalProperties": false
}

=== afaf-tech/sholawat-json/sholawat/burdah/dalail_khairat/fasl/4.json
{
    "number": 4,
    "source": "dalail-khairat",
    "name": "الْفَصْلُ الرّابِعُ فِي مَوْلِدِهِ عَلَيْهِ الصَّلَاةُ والسَّلَام",
    "latin": null,
    "text": {
        "1": {
            "arabic": "أَبَانَ مَوْلِدُهُ عَنْ طِيبِ عُنْصُرِهِ۞يَا طِيبَ مُبْتَدَإٍ مِنْهُ وَمُخْتَتَمِ",
            "latin": "Abāna mawliduhu ʿan ṭībi ʿunṣurihi۞Yā ṭība mubtadaʾin minhu wa mukhtatami"
        },
        "2": {
            "arabic": "يَوْمٌ تَفَرَّسَ فِيهِ الفُرْسُ أَنَّهُمُ۞قَدْ أُنْذِرُوا بِحُلُولِ البُؤْسِ وَالنِّقَمِ",
            "latin": "Yawmun tafarrasa fīhil fursu annahumu۞Qad undhirū biḥulūlil buʾsi wan niqami"
        },
        "3": {
            "arabic": "وَبَاتَ إِيوَانُ كِسْرَى وَهُوَ مُنْصَدِعٌ۞كَشَمْلِ أَصْحَابِ كِسْرَى غَيْرَ مُلْتَئِمِ",
            "latin": "Wa bāta īwānu kisrā wa huwa munṣadiʿun۞Ka shamli aṣ-ḥābi kisrā ghayra multaʾimi"
        },
        "4": {
            "arabic": "وَالنَّارُ خَامِدَةُ الأَنْفَاسِ مِنْ أَسَفٍ۞عَلَيْهِ وَالنَّهْرُ سَاهِي العَيْنِ مِنْ سَدَمِ",
            "latin": "Wan nāru khāmidatul anfāsi min asafin۞ʿAlayhi wan nahru sāhil ʿayni min sadami"
        },
        "5": {
            "arabic": "وَسَاءَ سَاوَةَ أَنْ غَاضَتْ بُحَيْرَتُهَا۞وَرُدَّ وَارِدُهَا بِالغَيْظِ حِينَ ظَمِي",
            "latin": "Wa sāʾa sāwata an ghāḍat buḥayratuhā۞Wa rudda wāriduhā bil ghayẓi ḥīna ẓamī"
        },
        "6": {
            "arabic": "كَأَنَّ بِالنَّارِ مَا بِالمَاءِ مِنْ بَلَلٍ۞حُزْنًا وَبِالمَاءِ مَا بِالنَّارِ مِنْ ضَرَمِ",
            "latin": "Ka anna bin nāri mā bil māʾi min balalin۞Ḥuznan wa bil māʾi mā bin nāri min ḍarami"
        },
        "7": {
            "arabic": "وَالجِنُّ تَهْتِفُ وَالأَنْوَارُ سَاطِعَةٌ۞وَالحَّقُ يَظْهَرُ مِنْ مَعْنىً وَمِنْ كَلِمِ",
            "latin": "Wal jinnu tahtifu wal anwāru sāṭiʿatun۞Wal ḥaqqu yaẓ-haru min maʿnan wa min kalimi"
        },
        "8": {
            "arabic": "عَمُوا وَصَمُّوا فَإِعْلاَنُ البَشَائِرِ لَمْ۞يُسْمَعْ وَبَارِقَةُ الإِنْذَارِ لَمْ تُشَمِ",
            "latin": "ʿAmmū wa ṣammū fa iʿlānul bashāʾiri lam۞Yusmaʿ wa bāriqatul indhāri lam tushami"
        },
        "9": {
            "arabic": "مِنْ بَعْدِ مَا أَخْبَرَ الأَقْوَامَ كَاهِنُهُمْ۞بِأَنَّ دِينَهُمُ المُعْوَجَّ لَمْ يَقُمِ",
            "latin": "Min baʿdi mā akhbaral aqwāma kāhinuhum۞Bi anna dīnahumul muʿwajja lam yaqumi"
        },
        "10": {
            "arabic": "وَبَعْدَمَا عَايَنُوا فِي الأُفْقِ مِنْ شُهُبٍ۞مُنْقَضَّةٍ وَفْقَ مَا فِي الأَرْضَ مِنْ صَنَمِ",
            "latin": "Wa baʿda mā ʿāyanū fīl ufqi min shuhubin۞Munqaḍḍatin wifqa mā fīl arḍi min ṣanami"
        },
        "11": {
            "arabic": "حَتَّى غَدَا عَنْ طَرِيقِ الْوَحْيِ مُنْهَزِمٌ۞مِنَ الشَّيَاطِينِ يَقْفُوا إِثْرَ مُنْهَزِمِ",
            "latin": "Ḥattā ghadā ʿan ṭarīqil waḥyī munhazimun۞Minash shayāṭīni yaqfū ithra munhazimi"
        },
        "12": {
            "arabic": "كَأَنَّهُمْ هَرَبًا أَبْطَالُ أَبْرَهَةٍ۞أَوْ عَسْكَرٍ بِالحَصَى مِنْ رَاحَتَيْهِ رُمِي",
            "latin": "Ka annahum haraban abṭālu abrahatin۞Aw ʿaskarin bil ḥaṣā min rāḥatayhi rumī"
        },
        "13": {
            "arabic": "نَبْذًا بِهِ بَعْدَ تَسْبِيحٍ بِبَطْنِهِمَا۞نَبْذَ المُسَبِّحِ مِنْ أَحْشَاءِ مُلْتَقِمِ",
            "latin": "Nabdhan bihi baʿda tasbīḥin bi baṭnihimā۞Nabdhal musabbiḥi min aḥshāʾi multaqimi"
        }
    },
    "translations": {
        "en": {
            "name": "Chapter Four: On The Prophet's Birth",
            "text": {
                "1": "His birth made the purity of his pedigree evident;O how pure were his beginning and his end!",
                "2": "On that day the Persians intuited that theyHad been warned of looming misery and retribution.",
                "3": "That night the throne room of Khusraw became cracked,Khusraw’s people, too, crumbled, never to be restored.",
                "4": "The sacred fire, grief-stricken, breathed its last,And the river [Euphrates] dried up out of worry.",
                "5": "Sāʾa was saddened by its lake drying up;the thirsty who went to drink there came back in a rage!",
                "6": "As if the fire, from sorrow, took on the water’s wetnessAnd water assumed the fire’s quality of blazing.",
                "7": "There were jinn calling out, and dazzling lightsAs truth was manifested in both word and reality.",
                "8": "They were blind and deaf, so the glad tidings proclaimedWent unheard, and the warning lightning-flash was not seen.",
                "9": "Even after the soothsayers had informed their peoplesThat their crooked religion would not endure,",
                "10": "And even after their eyes saw meteors on the horizonPlunging downwards, as idols were toppled on earth;",
                "11": "Until devils, routed, from the path of revelation,Fled in the wake of those who had been overpowered.",
                "12": "Fleeing like the brave warriors of AbrahaOr the army pelted by pebbles thrown by his hand,",
                "13": "Cast by him after glorifying Allah in the palm of his hand,As he who glorified his Lord was cast from the whale."
            }
        },
        "id": {
            "name": "",
            "text": {
                "1": "Kelahiran Baginda Nabi ﷺ menunjukkan kesucian unsur beliau.Betapa indah permulaan maupun penghujungnya.",
                "2": "Hari kelahiran Baginda Nabi ﷺ adalah hari di mana bangsa Persiatelah diingatkan para ahli nujum bahwa mereka akan ditimpa malapetaka dan siksa.",
                "3": "Pada malam itu, istana Kisra runtuh hancur terbelah,sebagaimana terpecah-belahnya pasukan Kisra yang tak dapat menyatu kembali.",
                "4": "Kobaran api sesembahan bangsa Persia padam akan kesedihan yang mendalam.Sungai pun berhenti mengalir sebab pedihnya duka.",
                "5": "Penduduk kawasan danau Sawah bersedih ketika danaunya mengering.Orang yang mendatanginya untuk mengambil air pun kembali dalam keadaan marah saat terjerat dahaga.",
                "6": "Karena duka yang mencekam, seakan-akan pada api bangsa Persia yang padam tersebut ada air danau Sawah,sedangkan dalam air danau yang kering itu terdapat api yang menyala.",
                "7": "Para jin menjerit. Cahaya terpancar tinggi ke angkasa.Dan kebenaran atas kenabian beliau tersingkap jelas dari makna maupun kata.",
                "8": "Mereka menjadi buta dan tuli. Kabar gembira kelahiran Baginda Nabi ﷺ pun takdapat mereka dengar, juga kilatan peringatan tak mereka lihat.",
                "9": "Mereka buta dan tuli setelah diberi kabar oleh para rahibbahwa agama mereka melenceng sesat dan tak akan bertahan abadi.",
                "10": "Dan setelah mereka saksikan bintang-bintang  di ufuk langitberjatuhan bertepatan dengan hancurnya berhala-berhala sesembahan di bumi.",
                "11": "Hingga para setan kabur terbirit-birit meninggalkan pintu langit, jalan wahyu ilahi.Mereka mengekor jejak setan yang lari tak henti-henti.",
                "12": "Para setan berlarian, sebagaimana panglima tentara Abrahahatau pasukan musuh yang lari dilempari kerikil oleh tangan mulia Baginda Nabi ﷺ.",
                "13": "Batu kerikil dilemparkan Baginda Nabi ﷺ setelah bertasbih dalam genggaman kedua tangan mulia beliau.Ini bagaikan terlemparnya Nabi Yunus n dari perut ikan paus setelah bertasbih di dalamnya."
            }
        }
    },
    "last_updated": "2024-12-11"
}

=== afaf-tech/sholawat-json/sholawat/burdah/minhaj_ul_quran/fasl/10.json
{
    "number": 10,
    "source": "minhaj-ul-quran",
    "name": "",
    "latin": null,
    "text": {
        "1": {
            "arabic": "賷賻賭丕 兀賻賰賿乇賻賲賻 丕賱賿禺賻賱賿賯賽 賲賻丕 賱賽賷 賲賻賳賿 兀賻賱購賵賿匕購 亘賽賴蹫爻賽賭賵賻丕賰賻 毓賽賳賿賭丿賻 丨購賱購賵賿賱賽 丕賱賿丨賻丕丿賽孬賽 丕賱賿毓賻賲賻賲賽"
        },
        "2": {
            "arabic": "賵賻賱賻賳賿 賷賾賻囟賽賷賿賯賻 乇賻爻購賭賵賿賱賻 丕賱賱賴賽 噩賻丕賴購賰賻 亘賽賷賿蹫廿賽匕賻丕 丕賱賿賰賻乇賽賷賿賲購 鬲賻噩賻賱賾賻賶 亘賽賭賭丕爻賿賲賽 賲購賳賿鬲賻賯賽賭賲賽"
        },
        "3": {
            "arabic": "賮賻廿賽賳賾賻 賲賽賳賿 噩購賵賿丿賽賰賻 丕賱丿賾購賳賿賷賻丕 賵賻囟賻乇賾賻鬲賻賴賻丕蹫賵賻賲賽賳賿 毓購賱購賵賿賲賽賰賻 毓賽賱賿賲購 丕賱賱賾賻賵賿丨賽 賵賻丕賱賿賯賻賱賻賲賽"
        },
        "4": {
            "arabic": "賷賻丕 賳賻賮賿賭爻購 賱丕 鬲賻賯賿賳賻胤賽賷 賲賽賳賿 夭賻賱賾賻丞賺 毓賻馗購賲賻鬲賿蹫廿賽賽賳賾賻 丕賱賿賰賻亘賻賭丕卅賽乇賻 賮賽賷 丕賱賿睾購賮賿乇賻丕賳賽 賰賻賭丕賱賱賾賻賲賻賭賲賽"
        },
        "5": {
            "arabic": "賱賻毓賻賭賱賾賻 乇賻丨賿賲賻丞賻 乇賻亘賾賽賷賿 丨賽賷賿賳賻 賷賻賯賿爻賽賭賭賲購賴賻丕蹫鬲賻兀賿鬲賽賷賿 毓賻賱賶 丨賻爻賻亘賽 丕賱賿毓賽氐賿賷丕賻賳賽 賮賽賷 丕賱賿賯賽爻賻賲賽"
        },
        "6": {
            "arabic": "賷賻丕 乇賻亘賾賽 賵賻丕噩賿毓賻賱賿 乇賻噩賻丕卅賽賷賿 睾賻賷賿乇賻 賲購賳賿毓賻賰賽爻賺蹫賱賻丿賻賷賿賭賰賻 賵賻丕噩賿毓賻賱賿 丨賽爻賻丕亘賽賷賿 睾賻賷賿乇賻 賲購賳賿禺賻乇賽賲賽"
        },
        "7": {
            "arabic": "賵賻丕賱賿胤購賮賿 亘賽毓賻亘賿丿賽賰賻 賮賽賷 丕賱丿賾賻丕乇賻賷賿賳賽 廿賽賽賳賾賻 賱賻賭賴購蹫氐賻亘賿乇丕賸 賲賾賻鬲侔賶 鬲賻賭丿賿毓購賴購 丕賱兀賻賴賿賭賵賻丕賱購 賷賻賳賿賴賻夭賽賲賽"
        },
        "8": {
            "arabic": "賵賻丕卅賿匕賻賳賿 賱賾賽爻購丨賿亘賽 氐賻賱丕丞賺 賲賾賽賳賿賰賻 丿賻丕卅賽賲賻丞賺蹫毓賻賭賱賻賶 丕賱賳賾賻亘賽賷賾賽 亘賽賲購賳賿賴賻賭賭賱賾賺 賵賾賻賲購賳賿爻賻賭噩賽賲賽"
        },
        "9": {
            "arabic": "賵賻丕賱丌賱賽 賵賻丕賱氐賾賻丨賿亘賽 孬購賲賾賻 丕賱鬲賾賻丕亘賽毓賽賷賿賳賻 賮賻賴購賭賲賿蹫兀賻賴賿賱購 丕賱鬲賾購賯侔賶 賵賻丕賱賳賾購賯侔賶 賵賻丕賱賿丨賽賱賿賲賽 賵賻丕賱賿賰賻賭乇賻賲賽"
        },
        "10": {
            "arabic": "孬購賲賾賻 丕賱乇賾賽囟賻賭丕 毓賻賳賿 兀賻亘賽賷賿 亘賻賰賿乇賺 賵賾賻毓賻賳賿 毓購賲賻乇賻蹫賵賻毓賻賳賿 毓賻賱賽賷賾賺 賵賾賻毓賻賳賿 毓購孬賿賲賻賭丕賳賻 匕賽賷 丕賱賿賰賻乇賻賲賽"
        },
        "11": {
            "arabic": "賲賻丕 乇賻賳賾賻丨賻鬲賿 毓賻匕賻亘賻丕鬲賽 丕賱賿亘賻丕賳賽 乇賽賷賿丨購 氐賻亘賻賭丕蹫賵賻兀賻胤賿乇賻亘賻 丕賱賿毓賽賷賿爻賻 丨賻丕丿賽賷 丕賱賿毓賽賷賿爻賽 亘賽丕賱賳賾賻睾賻賲賽"
        },
        "12": {
            "arabic": "賮賻丕睾賿賮賽乇賿 賱賽賳賻丕卮賽丿賽賴丕 賵賻丕睾賿賮賽乇賿 賱賽賯賻丕乇賽卅賽賴賻丕蹫爻賻丕賻賱賿鬲購賰賻 丕賱賿禺賻賷賿乇賻 賷賻丕 匕賻丕 丕賱賿噩購賵賿丿賽 賵賻丕賱賿賰賻乇賻賲賽"
        },
        "13": {
            "arabic": "賷賻丕 乇賻亘賾賽 亘賽丕賱賿賲購氐賿胤賻賮蹖 亘賻丕賱賾賽睾賿 賲賻賯賻丕氐賽丿賻賳賻丕蹫賵賻丕睾賿賮賽乇賿賱賻賳賻丕 賲賻丕賲賻囟蹖 賷賻丕 賵賻丕爻賽毓賻 丕賱賿讴賻乇賻賲賽"
        }
    },
    "translations": {
        "en": {
            "name": "Section Ten",
            "muqaddimah": " In this section Hadhrat Imaam Saalih Sharaf-ud-Deen Abu Abdullah Muhammad Bin Hasan Al-Busiri 乇丨賲丞 丕賱賱賴 毓賱賷賴 seeks refuge through the means of the Holy Prophet A. He 乇丨賲丞 丕賱賱賴 毓賱賷賴 has hope for forgiveness of his sins through the means and intercession of the Holy Prophet A. He recites Durood upon Nabi Akram (A), his family, four Orthodox Caliphs and his Companions y. He 乇丨賲丞 丕賱賱賴 毓賱賷賴 also asks Allah Almighty to forgive the writer of this poem and its reciter. ",
            "text": {
                "1": "The most generous of mankind, I do not have anyone to take shelter in except you at occurrence (at the time) of widespread calamity (last day, general resurrection).",
                "2": "And (O) Messenger of Allah (Almighty)! Because of me, your (highly) exalted status will not reduce. When the most bountiful (Allah Almighty) will show plainly (Himself) by the name of the punisher.",
                "3": "For verily, amongst your bounties is this world and the Hereafter; and the knowledge of Preserved Tablit (Lauh) and the Pen is the part of your knowledge.",
                "4": "My soul! Do not lose heart due to your capital sins. Verily, major sins in (the ocean of) pardon are minor.",
                "5": "(I) hope, the mercy of my Lord, when distributed, would be distributed in proportion (according) to the sins.",
                "6": "O my Lord! Make my hopes fulfilled by You and make not my accounting (calculation of deeds) destructive.",
                "7": "And (O my Lord)! Be kind to Your Servant in both the worlds; for verily, he has such patience (that) when (it is) called upon by hardship (it) runs away.",
                "8": "(O my Lord)! So order clouds of salutations (and blessings which) perpetually (send salutation) from You upon the Prophet (A to fall their rains of salutations upon himA) abundantly and gently.",
                "9": "And upon his (A) family (毓賱賷賴賲 丕賱爻賱丕賲) and his Companions (y), then upon those who follow them, (undoubtedly, they all are) the people of piety, knowledge, mercy and generosity.",
                "10": "(O my Lord)! Then be pleased with Abu Bakr, `Umar, `Ali and `Uthman (y) who are the people of nobility.",
                "11": "(O my Lord)! As long as the easterly breezing makes the branches of cypress rustle (means as long as this world is abide shower Your blessings on the Holy Prophet A) and (as long as) the camel rider make (his) camels march with (his) enchanting (and charming) songs.",
                "12": "(O my Lord)! Forgive its writer and its reader (for the sake of your beloved Prophet A; and) I ask all goodness of You. O (my Lord!) You are the Most Generous and the Most Bountiful.",
                "13": "O (Our) Lord! Fulfill (all of) our (good) objects and forgive us what has passed (in committing sins) for the sake of (Your Beloved Prophet) Mustafa (the chosen one A), O the Most bountiful (and the most generous)."
            }
        }
    },
    "last_updated": "2024-11-22"
}

=== afaf-tech/sholawat-json/sholawat/burdah/dalail_khairat/fasl/1.json
{
    "number": 1,
    "source": "dalail-khairat",
    "name": "الْفَصْلُ الْاوَّلُ فِي الْغَزَلِ وَشَكْوَىٰ الْغَرَامِ",
    "latin": null,
    "text": {
        "1": {
            "arabic": "أَمِنْ تَذَكُّرِ جِيرَانٍ بِذِي سَلَمِ۞مَزَجْتَ دَمْعًا جَرَى مِنْ مُقْلَةٍ بِدَمِ",
            "latin": "Amin tadhakkuri jīrānin bi dhī salami۞Mazajta damʿan jarā min muqlatin bidami"
        },
        "2": {
            "arabic": "أَمْ هَبَّتِ الرِّيحُ مِنْ تِلْقَاءِ كَاظِمَةٍ۞وَأَوْمَضَ البَرْقُ فِي الظَّلْمَاءِ مِنْ إِضَمِ",
            "latin": "Am habbatir rīhu min tilqāʾi kādhimatin۞Wa awmaḍal barqu fīẓ ẓulmāʾi min iḍami"
        },
        "3": {
            "arabic": "فَمَا لِعَيْنَيْكَ إِنْ قُلْتَ اكْفُفَا هَمَتَا۞وَمَا لِقَلْبِكَ إِنْ قُلْتَ اسْتَفِقْ يَهِمِ",
            "latin": "Famā li ʿaynayka in qultakfufā hamatā۞Wa mā li qalbika in qultastafiq yahimi"
        },
        "4": {
            "arabic": "أَيَحْسَبُ الصَّبُّ أَنَّ الحُبَّ مُنْكَتِمٌ۞مَا بَيْنَ مُنْسَجِمٍ مِنْهُ وَمُضْطَرِمِ",
            "latin": "Ayaḥsabuṣ ṣabbu annal ḥubba munkatimun۞Mā bayna munsajimin minhu wa muḍṭarimi"
        },
        "5": {
            "arabic": "لَوْلاَ الهَوَى لَمْ تَرِقْ دَمْعًا عَلَى طَلَلٍ۞وَلاَ أَرِقْتَ لِذِكْرِ البَانِ وَالْعَلَمِ",
            "latin": "Lawlal hawā lam turiq damʿan ʿalā ṭalalin۞Wa lā ariqta li dhikril bāni wal ʿalami"
        },
        "6": {
            "arabic": "فَكَيْفَ تُنْكِرُ حُبًّا بَعْدَمَا شَهِدَتْ۞بِهِ عَلَيْكَ عُدُولُ الدَّمْعِ وَالسَّقَمِ",
            "latin": "Fakayfa tunkiru ḥubban baʿda mā shahidat۞Bihi ʿalayka ʿudūlud damʿi was saqami"
        },
        "7": {
            "arabic": "وَأَثْبَتَ الوَجْدُ خَطَّيْ عَبْرَةٍ وَضَنىً۞مِثْلَ البَهَارِ عَلَى خَدَّيْكَ وَالعَنَمِ",
            "latin": "Wa athbatal wajdu khaṭṭay ʿabratin wa ḍanā۞Mithlal bahāri ʿalā khaddayka wal ʿanami"
        },
        "8": {
            "arabic": "نَعَمْ سَرَى طَيْفُ مَنْ أَهْوَى فَأَرَّقَنِي۞وَالحُبُّ يَعْتَرِضُ اللَّذَّاتَ بِالأَلَمِ",
            "latin": "Naʿam sarā ṭayfu man ahwā fa arraqanī۞Wal ḥubbu yaʿtariḍul ladhdhati bil alami"
        },
        "9": {
            "arabic": "يَا لاَئِمِي فِي الهَوَى العُذْرِيِّ مَعْذِرَةً۞مِنِّي إِلَيْكَ وَلَوْ أَنْصَفْتَ لَمْ تَلُمِ",
            "latin": "Yā lāʾimī fīl hawal ʿudhriyyi maʿdhiratan۞Minnī ilayka wa law anṣafta lam talumi"
        },
        "10": {
            "arabic": "عَدَتْكَ حَالِي لاَ سِرِّي بِمُسْتَتِرٍ۞عَنِ الْوُشَاةِ وَلاَ دَائِي بِمُنْحَسِمِ",
            "latin": "ʿAdatka ḥāliya lā sirrī bi mustatirin۞ʿAnil wushāti wa lā dāʾī bimunḥasimi"
        },
        "11": {
            "arabic": "مَحَّضْتَنِي النُصْحَ لَكِنْ لَسْتُ أَسْمَعُهُ۞إِنَّ المُحِبَّ عَنْ العُذَّالِ فِي صَمَمِ",
            "latin": "Maḥḥaḍtanī nuṣḥa lākin lastu asmaʿuhu۞Innal muḥibba ʿanil ʿudhdhāli fī ṣamami"
        },
        "12": {
            "arabic": "إِنِّي اتَّهَمْتُ نَصِيحَ الشَّيْبِ فِي عَذَليِ۞وَالشَّيْبُ أَبْعَدُ فِي نُصْحِ عَنِ التُّهَمِ",
            "latin": "Innit tahamtu naṣīḥash shaybi fī ʿadhalī۞Wash shaybu abʿadu fī nuṣḥin ʿanit tuhami"
        }
    },
    "translations": {
        "en": {
            "name": "Chapter One: Nostalgic Rhapsody and Love Complaint",
            "text": {
                "1": "Is it from remembering neighbours at Dhū SalamThat you shed tears admixed with blood from your eyes?",
                "2": "Or because wind has blown from the direction of KāẓimaAnd lightning has flashed in the dark of Iḍam?",
                "3": "So what ails your eyes that when you tell them ‘stop’, they continue to weep still more?And what ails your heart that when you bid it awake, it wanders further in distraction?",
                "4": "Does the lovelorn man think that love can be hiddenBehind a torrent from his [eyes], or a heart’s raging fire?",
                "5": "But for passion, you would not shed tears at an abandoned camp,Or lie awake at night recalling the fragrant willow or the mountain;",
                "6": "So how can you deny this love when tears and sickness,truthful witnesses, have testified to it against you?",
                "7": "Lovesickness has etched two lines, of tears and gauntness,Upon your cheeks, like yellow spice and red ʿanam",
                "8": "Yes, my beloved’s apparition came to me and denied me sleep,For love always opposes pleasures with pain!",
                "9": "O you who blame me for this chaste love, pardon me!But had you judged fairly, you would not have blamed me.",
                "10": "May you be spared my condition! My secret cannot be concealedFrom detractors, nor is there any cure for my ailment!",
                "11": "You have given me sincere advice, but I cannot hear it;A lover’s ears are deaf to the reproaches of critics.",
                "12": "I hold suspect even the advice of my own grey hairs,Even though their advice is far from deception."
            }
        },
        "id": {
            "name": "",
            "text": {
                "1": "Apakah karena mengingat tetangga tercinta yang berada di Dzu Salamhingga air matamu mengalir deras bercampur darah?",
                "2": "Ataukah karena hembusan angin dari arah Kazhimah,atau kilauan cahaya kilat pada kegelapan dari arah Idham?",
                "3": "Mengapa dengan kedua matamu? Jika engkau menahan air mata, keduanya tetap basah.Ada apa dengan hatimu? Jika kau sadarkan, ia tetap gelisah.",
                "4": "Apakah pemabuk cinta mengira rasa cintanya dapat tersembunyidi balik deraian air mata dan gelora cinta di dada?",
                "5": "Andai bukan karena cinta, air matamu takkan mengalir saat melihat sisa reruntuhan rumah sang kekasihdan tidak pula engkau terjaga untuk mengenang pohon Ban dan bukit yang mengingatkanmu pada sang kekasih.",
                "6": "Bagaimana engkau masih mengingkari rasa cintamu, padahalair mata dan derita telah jujur bersaksi;",
                "7": "Dan derita cintamu telah meninggalkan dua garis bekas linangan air mata dan membuatmu kurus lemah,laksana bunga kuning di kedua pipi dan mawar merah?",
                "8": "Benar! Bayangan kekasihku selalu terlintas dalam benakku hingga membuatku terjaga.Begitulah cinta, dapat mendatangkan derita di balik kenikmatan.",
                "9": "Wahai, para pencelaku karena gelora cinta suci ini! Aku maklumi cacianmu.Seandainya engkau bersikap adil, niscaya kau takkan mencelaku.",
                "10": "Kau telah mengetahui keadaanku. Kini rahasiaku tak dapat tersembunyidari para pemfitnah, sedangkan penyakit yang menimpaku tak kunjung pulih.",
                "11": "Engkau begitu tulus menasihatiku, tapi aku tak pernah mendengarkannya.Sungguh, pecinta selalu tuli untuk mendengar pencaci.",
                "12": "Sungguh, aku telah menuduh nasihat ubanku ikut mencela.Padahal, nasihat uban sangat tulus dan tak layak dicurigai."
            }
        }
    },
    "last_updated": "2024-12-11"
}

=== afaf-tech/sholawat-json/sholawat/burdah/nu_online/fasl/4.json
{
    "number": 4,
    "source": "nu-online",
    "name": "الفصل الرابع: في مولده ",
    "latin": null,
    "text": {
        "1": {
            "arabic": "أَبَانَ مَوْلِدُهُ عَنْ طِيْبِ عُنْصُرِهِ ۞ يَا طِيْبَ مُفْتَتَحٍ مِنْهُ وَمُخْتَــــتَمِ",
            "latin": "Abânâ mauliduhu ‘an thîbi ‘unshurihi ۞ yâ thîba muftataḫin minhu wa mukhtatami"
        },
        "2": {
            "arabic": "يَوْمٌ تَفَرَّسَ فِيْـــهِ الفُرْسُ أَنَّهُـــمُو ۞ قَدْ أُنْذِرُوا بِحُلُوْلِ الْبُؤْسِ وَالنِّقَمِ",
            "latin": "Yaumun tafarrasa fîhil-fursu annahumu ۞ qad undzirû biḫulûlil-bu'si wan-niqami"
        },
        "3": {
            "arabic": "وَبَاتَ إِيْوَانُ كِسْرَى وَهْوَ مُنْصَدِعٌ ۞ كَشَمْلِ أَصْحَابِ كِسْرَى غَيْرِ مُلْتَئِمِ",
            "latin": "Wa bâta îwânu kisrâ wahwa munshadi‘i ۞ kasyamli ashḫâbi kisrâ ghairi multa`imi"
        },
        "4": {
            "arabic": "وَالنَّارُ خَامِدَةُ الْأَنْفَاسِ مِنْ أَسَفٍ ۞ عَلَيْهِ وَالنَّهْرُ سَاهِيْ العَيْنِ مِنْ سَدَمِ",
            "latin": "Wan-nâru khâmidatul-anfâsi min asafin ۞ ‘alaihi wan-nahru sâhîl-‘aini min sadami"
        },
        "5": {
            "arabic": "وَسَآءَ سَاوَةَ أَنْ غَاضَتْ بُحَيْرَتُهَا ۞ وَرُدَّ وَارِدُهَا بِالْغَيْظِ حِيْنَ ظَمِيْ",
            "latin": "Wa sâ'a sâwata an ghâdlat buḫairatuhâ ۞ wa rudda wâriduhâ bil-ghaidhi ḫîna dhamî"
        },
        "6": {
            "arabic": "كَأَنَّ بِالنَّارِ مَا بِالْمَـــآءِ مِنْ بَلَلٍ ۞ حُزْنًا وَبِالْمَآءِ مَا بِالنَّارِ مِنْ ضَرَمِ",
            "latin": "Ka 'anna bin-nâri mâ bil-mâ'i min balalin ۞ ḫuznan wa bil-mâ'i mâ bin-nâri min dharami"
        },
        "7": {
            "arabic": "وَالْجِنُّ تَهْتِفُ وَالْأَنْوَارُ سَاطِعَةٌ ۞ وَالْحَقُّ يَظْهَرُ مِنْ مَّعْنًى وَمِنْ كَلِـــمِ",
            "latin": "Wal-jinnu tahtifu wal-anwâru sâthi‘atun ۞ wal-ḫaqqu yadh-haru min ma‘nan wa min kalimi"
        },
        "8": {
            "arabic": "عَمُوْا وَصَمُّوا فَإِعْلَانُ الْبَشَائِرِ لَمْ ۞ تُسْمَعْ وَبَـــارِقَةُ الْإِنْذَارِ لَمْ تُشَمِ",
            "latin": "‘Amû wa shammû fa i‘lânul-basyâ'iri lam ۞ tusma’ wa bâriqatul-indzâri lam tusyami"
        },
        "9": {
            "arabic": "مِنْ بَعْدِ مَا أَخْـــبَرَ الْأَقْوَامَ كَاهِنُهُـــمْ ۞ بِأَنَّ دِيْنَهُمُ الْمُعْوَجَّ لَمْ يَقُـــمِ",
            "latin": "Min ba’di mâ akhbaral-aqwâma kâhinuhum ۞ bi anna dînahumul-mu’awwaju lam yaqumi"
        },
        "10": {
            "arabic": "وَبَعْدَمَا عَايَنُوْا فِيْ الْأُفُقِ مِنْ شُهُبٍ ۞ مُنْقَضَّةٍ وَّفْقَ مَا فِيْ الْأَرْضِ مِنْ صَنَمِ",
            "latin": "Wa ba‘da mâ ‘âyanû fil-ufuqi min syuhubin ۞ munqadldlatin wafqa mâ fil-ardli min shanami"
        },
        "11": {
            "arabic": "حَتَّى غَدَا عَنْ طَرِيقِ الْوَحْيِ مُنْهَزِمٌ ۞ مِنَ الشَّيَاطِيْنِ يَقْفُو إِثْرَ مُنْهَزِمِ",
            "latin": "Ḫattâ ghadâ ‘an tharîqil-waḫyi munhazimun ۞ minasy-syayâthîni yaqfû itsra munhazimi"
        },
        "12": {
            "arabic": "كَأَنَّهُمْ هَرَبًــــا أَبْطَالُ أَبْرَهَـــةٍ ۞ أَوْ عَسْكَرٌ بِالْحَصَى مِنْ رَاحَتَيْهِ رُمِيْ",
            "latin": "Ka'annahum haraban abthâlu abrahatin ۞ au ‘askarun bil-ḫashâ min râḫataihi rumî"
        },
        "13": {
            "arabic": "نَبْذًا بِهِ بَعْدَ تَسْبِيحٍ بِبَطْنِهِمَا ۞ نَبْذَ الْمُسَبِّحِ مِنْ أَحْشَآءِ مُلْتَقِمِ",
            "latin": "Nabdzan bihi ba‘da tasbîhin bibathnihimâ ۞ nabdzal-musabbiḫi min aḫsyâ'i multaqimi"
        }
    },
    "translations": {
        "id": {
            "name": "Bab IV: Kelahiran Rasulullah ﷺ",
            "text": {
                "1": "Kelahiran sang nabi menampakkan kesucian diri. Alangkah indah permulaannya, juga indah penghabisannya",
                "2": "Hari kelahiran Rasulullah saat ada firasat bangsa Persia, bahwa ada peringatan kepada mereka datangnya bencana dan siksa",
                "3": "Saat menjelang malam tiba istana kisra hancur terbelah. Sebagaimana kumpulan sahabat kisra tiada menyatu terpecah belah",
                "4": "Api sesembahan padam karena duka yang mencekam. Sungai Eufrat tak mengalir, muram karena susah yang amat dalam",
                "5": "Penduduk negeri sawah resah duka saat danaunya kering keronta. Pengambil air kembali dengan tangan hampa kecewa ketika terjerat rasa dahaga",
                "6": "Seakan akan pada api nan membara terdapat cairan air karena duka. Dan pada air nan sejuk segar api yang membakar",
                "7": "Para jin menjerit, suara cahaya membumbung ke angkasa. Kebenaran tampak nyata dari makna maupun kata",
                "8": "Mereka buta dan tuli tak dengar hingga kabar gembira tiada didengar. Begitu juga kilatan peringatan sama sekali tak terhiraukan",
                "9": "Para rahib mereka telah kabarkan berita. Bahwa agama mereka melenceng, dan tak kan bertahan lama",
                "10": "Setelah mereka menyaksikan bintang-bintang di ufuk berjatuhan. Bersamaan di bumi ada kejadian berhala-berhala runtuh bergelimpangan",
                "11": "Hingga lenyap syetan berlari terbirit-birit dari pintu langit jalan wahyu ilahi. Mereka lari mengikuti syetan nan berlari tak henti",
                "12": "Mereka berlarian laksana lasykar Raja Abrahah. Atau bak pasukan yang dihujani kerikil oleh tangan Rasul",
                "13": "Batu yang nabi lemparkan, setelah bertasbih dalam genggaman. Bak terlemparnya nabi yunus dari perut ikan paus"
            }
        }
    },
    "last_updated": "2024-11-10"
}
