=== afaf-tech/sholawat-json/schemas/diba_fasl_v1.0.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Diba Fasl Schema",
    "version": "1.0",
    "type": "object",
    "properties": {
        "number": {
            "type": "integer",
            "minimum": 1,
            "description": "The chapter number."
        },
        "source": {
            "type": "string",
            "description": "The source of the text."
        },
        "name": {
            "type": "string",
            "description": "The Arabic name of the fasl (chapter)."
        },
        "latin": {
            "type": [
                "string",
                "null"
            ],
            "description": "The transliteration of the chapter name."
        },
        "sections": {
            "type": "object",
            "patternProperties": {
                "^[0-9]+$": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string",
                            "enum": [
                                "rawi",
                                "bari",
                                "closing"
                            ]
                        },
                        "text": {
                            "type": "object",
                            "patternProperties": {
                                "^[0-9]+$": {
                                    "type": "object",
                                    "properties": {
                                        "arabic": {
                                            "type": "string",
                                            "description": "The Arabic text of the verse."
                                        },
                                        "latin": {
                                            "type": [
                                                "string",
                                                "null"
                                            ],
                                            "description": "The transliteration of the Arabic text."
                                        }
                                    },
                                    "required": [
                                        "arabic"
                                    ]
                                }
                            },
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "type",
                        "text"
                    ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "translations": {
            "type": "object",
            "description": "Translations in various languages.",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "muqaddimah": {
                            "type": "string",
                            "description": "(introduction) of the chapter."
                        },
                        "translator": {
                            "type": "string",
                            "description": "translator of the chapter."
                        },
                        "sections": {
                            "type": "object",
                            "patternProperties": {
                                "^[0-9]+$": {
                                    "type": "object",
                                    "properties": {
                                        "text": {
                                            "type": "object",
                                            "patternProperties": {
                                                "^[0-9]+$": {
                                                    "type": "string"
                                                }
                                            },
                                            "additionalProperties": false
                                        }
                                    },
                                    "required": [
                                        "text"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "sections"
                    ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "last_updated": {
            "type": "string",
            "format": "date",
            "pattern": "^(\\d{4})-(\\d{2})-(\\d{2})$",
            "description": "The date when the data was last updated, in ISO 8601 date format (e.g., '2024-11-09')."
        }
    },
    "required": [
        "number",
        "source",
        "name",
        "last_updated"
    ],
    "anyOf": [
        {
            "required": [
                "sections"
            ]
        },
        {
            "required": [
                "translations"
            ]
        }
    ],
    "additionalProperties": false
}

=== afaf-tech/sholawat-json/sholawat/diba/nu_online/fasl/29.json
{
    "number": 29,
    "source": "nu-online",
    "name": "",
    "latin": "Doa Maulid ad-Diba’i",
    "sections": {
        "1": {
            "name": "",
            "type": "rawi",
            "text": {
                "1": {
                    "arabic": "اَلْحَمْدُ لِلّٰهِ رَبِّ الْعَـــالَمِيْنَ. اَللّٰهُمَّ صَلِّ وَسَلِّمْ عَلٰى سَيِّدِنَا مُحَمَّدٍ وَعَلَى اٰلِهٖ وَصَحْبِهٖ أَجْمَعِيْن. جَعَلَنَا اللهُ وَإِيَاكُمْ مِمَّنْ يَسْتَوْجِبُ شَفَاعَتَهُ. وَيَرْجُوْ بِذٰلِكَ رَحْمَتَهُ وَرَأْفَتَهُ. اَللّٰهُمَّ بِحُرْمَةِ هٰذَا النَّبِيِّ الْكَرِيْمِ. وَاٰلِهِ وَأَصْحَابِهِ السَّالِكِيْنَ عَلَى مَنْهَجِهِ الْقَوِيْمِ. اِجْعَلْنَا مِنْ خِيَارِ أُمَّتِهٖ. وَاسْتُرْنَا بِذَيْلِ حُرْمَتِهِ. وَاحْشُـرْنَا غَدًا فِيْ زُمْرَتِهِ. وَاسْتَعْمِلْ أَلْسِنَتَنَا فِيْ مَدْحِهٖ وَنُصْـرَتِهِ. وَأَحْيِنَا مُتَمَسِّكِيْنَ بِسُنَّتِهِ وَطَاعَتِهِ. وَأَمِتْنَا عَلَى حُبِّهٖ وَجَمَاعَتِهِ. اَللّٰهُمَّ أَدْخِلْنَا مَعَهُ الْجَنَّةَ فَإِنَّهُ أَوَّلُ مَنْ يَدْخُلُهَا. وَأَنْزِلْنَا مَعَهٗ فِيْ قُصُوْرِهَا. فَإِنَّهُ أَوَّلُ مَنْ يَنْزِلُهَا. وَارْحَمْنَا يَوْمَ يَشْفَعُ لِلْخَلَآئِقِ فَتَرْحَمُهَا. اَللّٰهُمَّ ارْزُقْنَا زِيَارَتَهٗ فِيْ كُلِّ سَنَةٍ. وَلَا تَجْعَلْنَا مِنَ الْغَافِلِيْنَ عَنْكَ وَلَا عَنْهُ قَدْرَ سِنَةٍ. اَللّٰهُمَّ لَا تَجْعَلْ فِيْ مَجْلِسِنَا هٰذَا أَحَدًا إِلَّا غَسَلْتَ بِمَاءِ التَّوْبَةِ ذُنُوْبَهُ. وَسَتَرْتَ بِرِدَآءِ الْمَغْفِرَةِ عُيُوْبَهُ. اَللّٰهُمَّ إِنَّهٗ كَانَ مَعَنَا فِي السَّنَةِ الْمَاضِيَةِ إِخْوَانٌ مَنَعَهُمُ الْقَضَآءُ عَنِ الْوُصُوْلِ إِلَى مِثْلِهَا. فَلَا تَحْرِمْهُمْ مِنْ ثَوَابِ هٰذِهِ اللَّيْلَةِ وَفَضْلِهَا. اَللّٰهُمَّ ارْحَمْنَا إِذَا صِرْنَا مِنْ أَصْحَابِ الْقُبُوْرِ. وَوَفِّقْنَا لِعَمَلٍ صَالِحٍ يَبْقٰى سَنَاهُ عَلَى مَمَرِّ الدُّهُوْرِ. اَللّٰهُمَّ اجْعَلْنَا لِاٰلَآئِكَ ذَاكِرِيْنَ. وَلِنَعْمَآئِكَ شَاكِرِيْنَ. وَلِيَوْمِ لِقَآئِكَ مِنَ الذَّاكِرِيْنَ. وَأَحْيِنَا بِطَاعَتِكَ مَشْغُوْلِيْنَ. وَإِذَا تَوَفَّيْتَنَا فَتَوَفَّنَا غَيْرَ مَفْتُوْنِيْنَ وَلَا مَخْذُوْلِيْنَ. وَٱخْتِمْ لَنَا مِنْكَ بِخَيْرٍ أَجْمَعِيْنَ. اَللّٰهُمَّ اكْفِنَا شَرَّ الظَّالِمِيْنَ. وَاجْعَلْنَا مِنْ فِتْنَةِ هٰذِهِ الدُّنْيَا سَالِمِيْنَ. اَللّٰهُمَّ اجْعَلْ هٰذَا الرَّسُوْلَ الْكَرِيْمَ لَنَا شَفِيْعًا. وَارْزُقْنَا بِهِ يَوْمَ الْقِيَامَةِ مَقَامًا رَفِيْعًا. اَللّٰهُمَّ اسْقِنَا مِنْ حَوْضِ نَبِيِّكَ مُحَمَّدٍ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ شَرْبَةً هَنِيْئَةً لَا نَظْمَأُ بَعْدَهَا أَبَدًا. وَاحْشُــرْنَا تَحْتَ لِوَآئِهِ غَدًا. اَللّٰهُمَّ اغْفِرْ لَنَا بِهٖ وَلِاٰبـَآئِنَا وَلِأُمَّهَاتِنَا وَلِمَشَايِخِنَا وَلِمُعَلِّمِيْنَا. وَذَوِي الْحُقُوْقِ عَلَيْنَا. وَلِجَمِيْعِ الْمُؤْمِنِيْنَ وَالْمُؤْمِنَاتِ. وَالْمُسْلِمِيْنَ وَالْمُسْلِمَاتِ. اَلْأَحْيَآءِ مِنْهُمْ وَالْأَمْوَاتِ. إِنَّكَ كَرِيْمٌ مُجِيْبُ الدَّعَوَاتِ. وَقَاضِي الْحَاجَاتِ. وَغَافِرُ الذُّنُوْبِ وَالْخَطِيْئَاتِ. يَا أَرْحَمَ الرَّاحِمِيْنَ. وَصَلَّى اللهُ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى اٰلِهِ وَصَحْبِهٖ وَسَلَّمَ. سُبْحَانَ رَبِّــكَ رَبِّ الْعِزَّةِ عَمَّا يَصِفُوْنَ. وَسَلَامٌ عَلَى الْمُرْسَلِيْنَ. وَالْحَمْدُ ِللّٰهِ رَبِّ الْعَالَمِيْنَ. اَلْفَاتِحَة",
                    "latin": "Al-ḫamdulillâhi rabbil-‘âlamîn, allâhumma shalli ‘alâ sayyidinâ muḫammadin wa ‘alâ âlihî wa shaḫbihi ajma‘îna, ja‘alanâllâhu wa iyâkum mimman yastaujibu syafâ’atahu, wa yarjû bidzâlika raḫmatahu wa ra’fatahu, allâḫumma biḫurmati hâdzan-nabiyyil-karîmi, wa âlihi wa ashḫâbihis-sâlikîna ‘alâ manhajihil-qawîmi, ij‘alnâ min khiyâri ummatihi, wasturnâ bidzaili ḫurmatihi, waḫsyurnâ ghadan fî zumratihi, wasta‘mil alsinatanâ fî madḫihi wa nushratihi, wa aḫyinâ mutamassikîna bisunnatihi wathâ‘atihi, wa amitnâ ‘alâ ḫubbihi wa jamâ‘atihi, allâḫumma adkhilnâ ma‘ahul-jannata fainnahu awwalu man yadkhuluhâ, wa anzilnâ ma‘ahu fî qushûrihâ, fainnahu awwalu man yanziluhâ, warḫamnâ yauma yasyfa‘u lil-khalâ’iqi fatarḫamuhâ, allâḫummar-zuqnâ ziyâratahu fî kulli sanatin, walâ taj‘alnâ minal-ghâfilîna anka wa lâ ‘anhu qadra sinatin, allâḫumma lâ taj‘aln fî majlisinâ hâdzâ aḫadan illâ ghasalta bimâ’it-taubati dzunûbahu, wa satarta biridâ’il-maghfirati ‘uyûbahu, allâḫumma innahu kâna ma‘anâ fis-sanatil-mâdliyati, ikhwânun mana‘ahumul-qadlâ’u ‘anil-wushûli ilâ mitslihâ, falâ taḫrimhum min tsawâbi hâdzihil-lailati wafadllihâ, allâḫummarḫamnâ idzâ shirnâ min ashḫâbil-qubûri, wawaffiqnâ li‘amailshâliḫi yabqâ sanâhu ‘alâ mamarrid-duhûri, allâḫumj‘alnâ li’âlâ’ika dzâkirîn, wa lina‘mâ’ika syâkirîna, wa liyaumi liqâ’ika minadz-dzâkirîna, waḫyinâ bithâ‘atika masyghûlina, wa idzâ tawaffaitanâ fatawaffanâ ghaira maftûnîna, wa lâ makhdzûlîna, wakhtim lanâ minka bikhairi ajma‘îna, allâḫummakfinâ syarradh-dhâlimîn, waj‘alnâ min fitnati hâdzihid-dunyâ sâlimîn, allâḫuj‘al hâdzar-rasûlal-karîma lanâ syafî‘an, warzuqnâ bihi yaumal-qiyâmati maqâman rafî‘an, allâhummas-qinâ min ḫaudli nabiyyika muḫammadin shallallâhu ‘alaihi wa sallama syarbatan hanî’atan lâ nadhma’a ba‘dahâ abadan, waḫsyurnâ taḫta liwâ’ihi ghadzan, allâḫummaghfir lanâ bihî wa li’abâ’inâ wa li’ummahâtinâ wa limasyâyikhinâ wa limu‘alliminâ, wa dzawil-ḫuqûqi ‘alaina, wa lijamî‘il-mu’minîna wal-mu’minât, wal-muslimîna wal-muslimâti, al-aḫyâ’i minhum wal-amwâti, innaka karîmun mujîbud-da‘awâti, wa qâdliyal-ḫâjâti, wa ghâfirudz-dzunûbi wal-khathî’âti, yâ arḫamar-raḫimîna, wa shallallâḫu ‘alâ sayyidinâ muḫammadin wa ‘alâ âlihi wa shaḫbihi wa sallam, subḫânaka rabbika rabbil-‘izzati ‘ammâ yashifûna, wa salâmun ‘alal-mursalîna, wal-ḫamdulillâhi rabbil-‘âlamîna, al-fâtiḫah."
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "اَللّٰهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَيْهِ",
                    "latin": "Allâhumma shalli wa sallim wa bârik 'alaihi wa 'alâ âlihi"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Segala puji bagi Allah Tuhan seru sekelian alam. Ya Allah limpahkanlah rahmat dan salam atas Junjungan kami Nabi Muhammad dan atas keluarga serta sahabatnya sekalian. semoga Allah menjadikan kami dan kamu sekalian dari golongan orang yang mendapat syafaatnya; Serta mengharapkan rahmat dan kasih sayangnya dari Allah. Ya Allah dengan kehormatan Nabi yang mulia ini dan keluarga serta sahabatnya yang berjalan atas petunjuk Nabi yang kokoh. Jadikanlah kami termasuk umatnya yang terpilih. Tutuplah segala kekurangan kami. Himpunkanlah kami kelak (Hari Mahsyar) didalam golongannya. Pergunakanlah lidah-lidah kami dalam memuji dan membelanya. Hidupkanlah kami dalam keadaan berpegang dengan sunnahnya dan ketaatannya, dari segala fitnah dunia. Ya Allah jadikanlah Rasul yang mulia ini orang yang memberi syafaat kepada kami. Matikanlah kami dalam kecintaan kepadanya dan dalam jemaahnya. Ya Allah masukkanlah kami kedalam syurga bersama-samanya kerana baginda orang yang mula-mula masuk ke dalamnya. Turunkanlah kami dalam mahligainya bersama-samanya kerana bagindalah orang yang mula turun kedalamnya. Kasihanilah kami dihari dia memberi syafaat kepada makhlok lalu engkau kasihani mereka. Ya Allah berilah kami peluang menziarahinya setiap tahun. Janganlah Engkau jadikan kami dari golongan orang yang lalai dari mengingatiMu dan juga lalai dari mengingatinya walau sekejap kadar terlelap. Ya Allah janganlah hendaknya ada di majlis kami ini orang yang berdosa melainkan Engkau cuci segala dosanya dengan air taubat; dan Engkau tutupi keaibannya dengan pakaian pengampunan. Ya Allah pada tahun yang lalu ada ikhwan kami yang tidak dapat menghadirkan diri pada tahun ini kerana dihalang oleh QadhaMu, maka janganlah Engkau haramkan pahala serta ganjaran yang Engkau turunkan pada saat ini. Ya Allah kasihanilah kami jika kami sudah menjadi ahlilkubur. Berilah kami Taufiq untuk membuat amal salih yang kekal cahayanya sepanjang zaman. Ya Allah jadikanlah kami orang yang ingat kepada pemberianMu, bersyukur atas nikmatMu, dan ingat kepada Hari Pertemuan denganMu. Hidupkanlah kami masyghul dengan ketaatan kepadaMu. Kiranya Engkau matikan kami. Matikanlah kami tanpa sebarang fitnah atau kekeciwaan. Sudahilah segala perkara kami dengan kebaikan daripadaMu. Ya Allah selamatkanlah kami dari kejahatan orang yang aniaya (3 kali) . Jadikanlah kami orang yang terselamat dari fitnah Dunia, dan kurniakanlah kami dengan sebabnya kedudukan yang tinggi diHari Qiamat kelak. Ya Allah berilah kami minum dari telaga Nabi Mu Muhammad ﷺ dengan minuman yang melegakan menyebabkan kami tidak rasa haus lagi selepasnya. Himpunkanlah kami di bawah panji-panjinya esok (Hari Mahsyar). Ya Allah dengan darjatnya disisiMu, ampunilah kami, kedua ibu bapa kami, guru-guru kami, orang-orang yang punya haq atas kami, serta sekalian mukminin mukminat, muslimin muslimat samada yang masih hidup mahu pun yang sudah wafat. Sesungguhnya Engkau memperkenankan segala doa, menunaikan segala hajat dan mengampuni segala dosa dan kesalahan. Ya Tuhan yang amat Pengasih dari semua yang kasih. Selawat dan salam Allah atas penghulu kami Muhammad dan atas keluarga serta sahabatnya. Mahasuci Tuhanmu yang mempunyai kemuliaan dari segala apa yang mereka sifatkan.Ucapan salam atas sekalian Rasul dan segala puji bagi Allah Tuhan seru sekalian alam. Al-Fatihah"
                    }
                },
                "2": {
                    "text": {
                        "1": "Ya Allah, limpahkan rahmat, kesalamatan, serta keberkahan kepada Nabi Muhammad beserta keluarga beliau"
                    }
                }
            }
        }
    },
    "last_updated": "2024-12-14"
}

=== afaf-tech/sholawat-json/sholawat/diba/nu_online/fasl/11.json
{
    "number": 11,
    "source": "nu-online",
    "name": "",
    "latin": "Awwalu mâ nastaftiḫu…",
    "sections": {
        "1": {
            "name": "",
            "type": "rawi",
            "text": {
                "1": {
                    "arabic": "أَوَّلُ مَا نَسْتَفْتِحُ بِـإِيْرَادِ حَدِيْثَيْنِ وَرَدَا عَنْ نَبِيٍّ كَانَ قَدْرُهٗ عَظِيْمًا. وَنَسَبُهٗ كَرِيْمًا. وَصِرَاطُهٗ مُسْتَقِيْمًا. قَالَ فِيْ حَقِّهٖ مَنْ لَّمْ يَزَلْ سَمِيْعًا عَلِيْمًا. إِنَّ اللهَ وَمَلَآئِكَتَهٗ يُصَلُّوْنَ عَلَى النَّبِيِّ. يَآأَيُّهَا الَّذِيْنَ اٰمَنُوْا صَلُّوْا عَلَيْهِ وَسَلِّمُوْا تَسْلِيْمًا",
                    "latin": "Awwalu mâ nastaftiḫu bi îrâdi ḫadîtsaini wa radâ ‘an nabiyyin kâna qadruhu ‘adhîman, wa nasabuhu karîman, wa shirâtûhu mustaqîman, qâla fî ḫaqqihî man lam yazal samî’an ‘alîman, innallâha wa malâ’ikatahu yushallûna ‘alan-nabiyyi, yâ ayyuhal-ladzîna âmanû shallû ‘alaihi wa sallimû taslîman."
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "اَللّٰهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَيْهِ",
                    "latin": "Allâhumma shalli wa sallim wa bârik 'alaihi wa 'alâ âlihi"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Pertama kali kami awali hal ini dengan mengemukakan dua buah hadits yang datang dari Nabi yang berkedudukan agung. Dan bernasab mulia serta lurus perjalanan hidupnya. Allah berfirman: Demi hak Muhammad. Dzat yang tiada terIepas dari sifat Maha Mendengar dan Maha Melihat, Bahwasanya Allah dan para malaikat-Nya selalu bershalawat untuk Nabi, wahai orang-orang yang beriman, bersholawatlah untuk beliau dan ucapkanlah salam kepadanya dengan bersungguh-sungguh."
                    }
                },
                "2": {
                    "text": {
                        "1": "Ya Allah, limpahkan rahmat, kesalamatan, serta keberkahan kepada Nabi Muhammad beserta keluarga beliau"
                    }
                }
            }
        }
    },
    "last_updated": "2024-12-14"
}

=== afaf-tech/sholawat-json/sholawat/simtudduror/nu_online/fasl/12.json
{
    "number": 12,
    "source": "nu-online",
    "name": "",
    "latin": "Fanasya-a shallallâhu…",
    "sections": {
        "1": {
            "name": "",
            "type": "rawi",
            "text": {
                "1": {
                    "arabic": "فَنَشَأَ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ عَلَى أَكْمَلِ الْأَوْصَاف. يَحُفُّهُ مِنَ اللهِ جَمِيْلُ الرِّعَايَةِ وَغَامِرُ الْأَلْطَاف. فَكَانَ يَشِبُّ فِي الْيَوْمِ شَبَابَ الصَّبِيِّ فيِ الشَّهْرِ. وَيَظْهَرُ عَلَيْهِ فِي صِبَاهُ مِنْ شَرَفِ الْكَمَالِ مَا يَشْهَدُ لَهُ بِأَنَّهُ سَيِّدُ وَلَدِ آدَمَ وَلَا فَخْر. وَلَمْ يَزَلْ وَأَنْجُمُ سُعُوْدِهِ طَالِعَة. وَالْكَائِنَاتُ لِعَهْدِهِ حَافِظَةٌ وَلِأَمْرِهِ طَائِعَة. فَمَا نَفَثَ عَلَى مَرِيْضٍ إِلَّا شَفَاهُ الله. وَلَاتَوَجَّهَ فِي غَيْثٍ إِلَّا وَأَنْزَلَهُ مَوْلَاه. حَتَّى بَلَغَ مِنَ الْعُمْرِ أَشُدَّه. وَمَضَتْ لَهُ مِنْ سِنِّ الشَّبَابِ وَالْكُهُوْلَةِ مُدَّة. فَاجَأَتْهُ الْحَضْرَةُ الْاِلٰـهِيَّةُ بِمَا شَرَّفَتْهُ بِهِ وَحْدَه. فَنَزَلَ عَلَيْهِ الرُّوْحُ الْأَمِيْن. بِالْبُشْرَى مِنْ رَبِّ الْعَالَمِيْن. فَتَلَا عَلَيْهِ لِسَانُ الذِّكْرِ الْحَكِيْمِ شَاهِدَ ﴿وَاِنَّكَ لَتُلَقَّى الْقُرْآنَ مِنْ لَدُنْ حَكِيْمٍ عَلِيْمٍ﴾ فَكَانَ أَوَّلَ مَا نَزَلَ عَلَيْهِ مِنْ تِلْكَ الْحَضْرَةِ مِنْ جَوَامِعِ الْحِكَم. قَوْلُهُ تَعَالَى : ﴿اِقْرَأ بِاسْمِ رَبِّكَ الَّذِيْ خَلَقَ. خَلَقَ الْإِنْسَانَ مِنْ عَلَقَ. اِقْرَأْ وَرَبُّكَ الْأَكْرَمُ. اَلَّذِيْ عَلَّمَ بِالْقَلَمِ. عَلَّمَ الْإِنْسَانَ مَا لَمْ يَعْلَم﴾ فَمَا أَعْظَمَهَا مِنْ بِشَارَةٍ أَوْصَلَتْهَا يَدُ الْإِحْسَان. مِنْ حَضْرَةِ الْاِمْتِنَان. إِلَى هٰذَا الْإِنْسَان. وَأَيَّدَتْهَا بِشَارَةُ ﴿اَلرَّحْمَنُ عَلَّمَ الْقُرْآنَ. خَلَقَ الْاِنْسَانَ عَلَّمَهُ الْبَيَانَ﴾ وَلَاشَكَّ أَنَّهُ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ هُوَ الْإِنْسَانُ الْمَقْصُوْدُ بِهٰذَا التَّعْلِيْم. مِنْ حَضْرَةِالرَّحْمٰنِ الرَّحِيْم",
                    "latin": "Fanasyâ’a shallallâhu ‘alaihi wa sallama ‘alâ akmalil-aushâfi, yaḫuffuhu minallâhi jamîlur-ri‘âyati wa ghâmirul-althâfi, fakâna yasyibbu fil-yaumi syabâbash-shabiyyi fisy-syahri, wa yadhharu ‘alaihi fî shibâhu min syarafil-kamâli mâ yasyhadu lahu bi annahu sayyidu waladi âdama wa lâ fakhr. Wa lam yazal wa anjumu su‘ûdihi thâli‘ah, wal-kâ’inâtu li‘ahdihi ḫafidhatun wa liamrihi thâ‘iah, famâ nafatsa ‘alâ marîdlin illâ syafâhullâhu, wa lâ tawajjaha fî ghaitsin illâ wa anzalahu maulâhu, ḫattâ balagha minal-‘umri asyuddahu, wa madlat lahu min sinnisy-syabâbi wal-kuhûlati muddati, faja’at hul-ḫadlratul-ilâhiyyatu bimâ syarrafat hu bihi waḫdahu, fanazala ‘alaihir-rûhul-amîn, bil-busyrâ min rabbil-‘âlamîna, fatalâ ‘alaihi lisânudz-dzikril-ḫakîmi syâhid ﴾wa innaka latulaqqâl-qur’âna min ladun ḫakîmin ‘alîm ﴿ fakâna awwala mâ nazala ‘alaihi min tilkal-ḫadlrati min jawâmi‘il-ḫikam. qauluhu ta‘âlâ: ﴾iqra bismi rabbiklal-ladzî khalaqa, khalaqal-insâna min ‘alaq, iqra wa rabbukal-akram, alladzî ‘allama bil-qalam, ‘allamal-insâna mâ lam ya‘lam﴿, famâ a‘dhamahâ min bisyâratin aushalat hâ yadul-iḫsân, min ḫadlratil-imtinân, ilâ hâdzal-insân, wa ayyadat hâ bisyâratu ﴾ar-raḫmanu ‘allamal-qur’âna, khalaqal-insâna ‘allamahul-bayâna﴿ wa lâ syakka annahu shallallâhu ‘alaihi wa sallama huwal-insânul-maqshûdu bihâdzat-ta‘lim, min ḫadlratir-raḫmânir-raḫîm."
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "﴿اَللّٰهُمَّ صَلِّ وَسَلِّمْ أَشْرَفَ الصَّلَاةِ وَالتَّسْلِيْمِ عَلَى سَيِّدِنَا وَنَبِيِّنَا مُحَمَّدٍ ࣙالرَّؤُوْفِ الرَّحِيْمِ﴾"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Rasulullah ﷺ tumbuh dengan sifat-sifat paling sempurna, dikelilingi selalu pemeliharaan Allah Maha Kuasa serta diliputi rahmat-Nya berlimpah-limpah. la tumbuh dalam sehari , seperti bayi lain dalam sebulan. Keluhuran pribadinya tampak sempurna sejak usianya yang amat muda menjadi saksi bahwa dialah penghulu keturunan Adam semuanya. Bintang-bintang kemujuran selalu bersamanya. Demikian pula segenap benda di alam ini menampakkan kesetiaan dan kepatuhan padanya. Tiap kali ia “meniupi” penderita sakit, niscaya Allah melimpahkan kesembuhan baginya. Tiap kali berdoa memohon hujan, niscaya Allah selalu menurunkannya. Demikian keadaannya sehari-hari, sampai ia telah melewati masa mudanya dan mencapai usia dewasa, saat itulah Allah mengkhususkannya, dengan kemuliaan hanya baginya seorang. Dan turunlah Jibril Ar-Ruhul Amin membawa kabar gembira dari Tuhan Seru Sekalian Alam, membacakan baginya ayat-ayat suci Al Quran Al-Hakim, “,…Dan sesungguhnya kepadamu telah diberikan Al-Qur’an dari hadirat Allah, yang Maha Bijaksana lagi Maha Mengetahui.” Adapun mula pertama diturunkan kepadanya, di antara ayat-ayat suci padat berisi, yang berasal dari hadirat Allah SWT ialah, “Bacalah dengan nama Tuhanmu, Yang mencipta manusia dari segumpal darah. Bacalah! Tuhanmulah yang paling mulia, Yang mengajar dengan kalam, mengajar manusia apa yang tidak ia tahu.” Oh… betapa agungnya kabar gembira ini! Karunia sempurna datang dari Allah Maha Pengasih lagi Maha pemurah ditujukan kepada insan mulia ini. Lalu dikuatkan lagi dengan firman-Nya, “Ar-Rahman, Tuhan Maha Pemurah, mengajarkan Al-Qur’an, mencipta insan, lalu diajarinya fasih perkataan…” Dan tiada syak lagi tentunya beliaulah insan yang dimaksud dengan pemberian ajaran itu darl hadirat Allah, yang Maha Rahman dan Rahim."
                    }
                },
                "2": {
                    "text": {
                        "1": "Limpahkan, ya Allah, semulia-mulia shalawat dan salam atas junjungan dan nabi kami, Muhammad SAW yang amat penyantun dan penyayang"
                    }
                }
            }
        }
    },
    "last_updated": "2024-11-16"
}

=== afaf-tech/sholawat-json/sholawat/diba/nu_online/fasl/19.json
{
    "number": 19,
    "source": "nu-online",
    "name": "",
    "latin": "Qîla man yakfulu…",
    "sections": {
        "1": {
            "name": "",
            "type": "rawi",
            "text": {
                "1": {
                    "arabic": "قِيْلَ مَنْ يَّكْفُلُ هٰذِهِ الدُّرَّةَ الْيَتِيْمَةَ. اَلَّتِيْ لَا تُوْجَدُ لَهَا قِيْمَةٌ. قَالَتِ الطُّيُوْرُ نَحْنُ نَكْفُلُهٗ وَنَغْتَنِمُ هِمَّتَهُ الْعَظِيْمَةَ. قَالَتِ الْوُحُوْشُ نَحْنُ أَوْلٰى بِذٰلِكَ لِكَيْ نَنَالَ شَرَفَهٗ وَتَعْظِيْمَهُ. قِيْلَ يَا مَعْشَرَ الْأُمَمِ اسْكُنُوْا فَإِنَّ اللهَ قَدْ حَكَمَ فِيْ سَابِقِ حِكْمَتِهِ الْقَدِيْمَةِ. بِأَنَّ نَبِيَّهٗ مُحَمَّدًا صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ يَكُوْنُ رَضِيْعًا لِحَلِيْمَةَ الْحَلِيْمَةِ",
                    "latin": "Qîla man yakfulu hâdzihid-durratal-yatîmata, allatî lâ tûjadu lahâ qîmatun, qâlatith-thûyûru naḫnu nakfuluhu wa naghtatimu himmatahul-‘adhîmata, qâlatil-wuḫûsyu naḫnu aula bidzâlika likai nanâla syarafahu wa ta’dhîmahu, qîla yâ ma‘syaral-umamis-kunû fa innallâha qad ḫakama fî sâbiqi ḫikmatihil-qadîmati, bianna nabiyyahu muḫammadan shallallâhu ‘alaihi wa sallama yakûnu radlî’an liḫalîmatal-ḫalîmah."
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "اَللّٰهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَيْهِ",
                    "latin": "Allâhumma shalli wa sallim wa bârik 'alaihi wa 'alâ âlihi"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Diserukan oleh malaikat: siapakah yang suka mengasuh anak yatim yang bagaikan permata yang tiada bandingnya kemahalan harganya..? Berkatalah sekelompok burung: kamilah yang sanggup mengasuh dan mengambil keuntungan cita-citanya yang agung. Betkatalah binatang-binatang liar: kamilah yamg lebih berhak mengasuhnya agar memperoleh kemuliaan dan keagunganya. Diserukan oleh Malaikat: hai golongan umat... Tenanglah kalian, karena sesungguhnya Allah benar-benar telah mutuskan sejak zaman dahulu kala, bahwasanya Nabi Muhammad ﷺ adalah hendak menyusu kepada seorang wanita bersama Siti Halimah yang penuh rasa kasih sayang"
                    }
                },
                "2": {
                    "text": {
                        "1": "Ya Allah, limpahkan rahmat, kesalamatan, serta keberkahan kepada Nabi Muhammad beserta keluarga beliau"
                    }
                }
            }
        }
    },
    "last_updated": "2024-12-14"
}
