=== afaf-tech/sholawat-json/schemas/diba_fasl_v1.0.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Diba Fasl Schema",
    "version": "1.0",
    "type": "object",
    "properties": {
        "number": {
            "type": "integer",
            "minimum": 1,
            "description": "The chapter number."
        },
        "source": {
            "type": "string",
            "description": "The source of the text."
        },
        "name": {
            "type": "string",
            "description": "The Arabic name of the fasl (chapter)."
        },
        "latin": {
            "type": [
                "string",
                "null"
            ],
            "description": "The transliteration of the chapter name."
        },
        "sections": {
            "type": "object",
            "patternProperties": {
                "^[0-9]+$": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string",
                            "enum": [
                                "rawi",
                                "bari",
                                "closing"
                            ]
                        },
                        "text": {
                            "type": "object",
                            "patternProperties": {
                                "^[0-9]+$": {
                                    "type": "object",
                                    "properties": {
                                        "arabic": {
                                            "type": "string",
                                            "description": "The Arabic text of the verse."
                                        },
                                        "latin": {
                                            "type": [
                                                "string",
                                                "null"
                                            ],
                                            "description": "The transliteration of the Arabic text."
                                        }
                                    },
                                    "required": [
                                        "arabic"
                                    ]
                                }
                            },
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "type",
                        "text"
                    ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "translations": {
            "type": "object",
            "description": "Translations in various languages.",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "muqaddimah": {
                            "type": "string",
                            "description": "(introduction) of the chapter."
                        },
                        "translator": {
                            "type": "string",
                            "description": "translator of the chapter."
                        },
                        "sections": {
                            "type": "object",
                            "patternProperties": {
                                "^[0-9]+$": {
                                    "type": "object",
                                    "properties": {
                                        "text": {
                                            "type": "object",
                                            "patternProperties": {
                                                "^[0-9]+$": {
                                                    "type": "string"
                                                }
                                            },
                                            "additionalProperties": false
                                        }
                                    },
                                    "required": [
                                        "text"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "sections"
                    ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "last_updated": {
            "type": "string",
            "format": "date",
            "pattern": "^(\\d{4})-(\\d{2})-(\\d{2})$",
            "description": "The date when the data was last updated, in ISO 8601 date format (e.g., '2024-11-09')."
        }
    },
    "required": [
        "number",
        "source",
        "name",
        "last_updated"
    ],
    "anyOf": [
        {
            "required": [
                "sections"
            ]
        },
        {
            "required": [
                "translations"
            ]
        }
    ],
    "additionalProperties": false
}

=== afaf-tech/sholawat-json/sholawat/diba/nu_online/fasl/7.json
{
    "number": 7,
    "source": "nu-online",
    "name": "",
    "latin": "Yub‘atsu min tihamah…",
    "sections": {
        "1": {
            "name": "",
            "type": "rawi",
            "text": {
                "1": {
                    "arabic": "يُبْعَثُ مِنْ تِهَامَةَ بَيْنَ يَدَيِ الْقِيَامَةِ. فِيْ ظَهْرِهٖ عَلَامَةٌ تُظِلُّهُ الْغَمَامَةُ. تُطِيْعُهُ السَّحَآئِبُ. فَجْرِيُّ الْجَبِيْنِ لَيْلِيُّ الذَّوَآئِبِ. أَلْفِيُّ الْأَنْفِ مِيْمِيُّ الْفَمِ نُوْنِيُّ الْحَاجِبِ. سَمْعُهٗ يَسْمَعُ صَرِيْرَ الْقَلَمِ بَصَرُهٗ إِلَى السَّبْعِ الطِّبَاقِ ثَاقِبٌ. قَدَمَاهٗ قَبَّلَهُمَا الْبَعِيْرُ فَأَزَالَا مَا اشْتَكَاهُ مِنَ الْمِحَنِ وَالنَّوَآئِبِ. اٰمَنَ بِهِ الضَّبُّ وَسَلَّمَتْ عَلَيْهِ الْأَشْجَارُ وَخَاطَبَتْهُ الْأَحْجَارُ وَحَنَّ إِلَيْهِ الْجِذْعُ حَنِيْنَ حَزِيْنٍ نَادِبٍ. يَدَاهُ تَظْهَرُ بَرَكَتُهُمَا فِي الْمَطَاعِمِ وَالْمَشَارِبِ. قَلْبُهٗ لَا يَغْفُلُ وَلَا يَنَامُ وَلٰكِنْ لِلْخِدْمَةِ عَلَى الدَّوَامِ مُرَاقِبٌ. إِنْ أُوْذِيَ يَعْفُ وَلَا يُعَاقِبُ. وَإِنْ خُوْصِمَ يَصْمُتْ وَلَا يُجَاوِبُ. أَرْفَعُهٗ إِلَى أَشْرَفِ الْمَرَاتِبِ. فِي رَكْبَةٍ لَا تَنْبَغِي قَبْلَهٗ وَلَا بَعْدَهٗ لِرَاكِبٍ. فِيْ مَوْكِبٍ مِنَ الْمَلَآئِكَةِ يَفُوْقُ عَلَى سَآئِرِ الْمَوَاكِبِ. فَإِذَا ارْتَقىٰ عَلَى الْكَوْنَيْنِ وَانْفَصَلَ عَنِ الْعَـــالَـمِـيْنَ، وَوَصَلَ إِلَى قَابِ قَوْسَيْنِ كُنْتُ لَهٗ اَنَا النَّدِيْمَ وَالْمُخَاطِبَ ",
                    "latin": "Yub‘atsu min tihâmata baina yadayil-qiyâmati, fî dhahrihi ‘alâmatun tudhilluhul-ghamâmatu, tuthî‘uhus-saḫâ’ibu,fajriyyul-jabîni lailiyyudz-dzawâ’ibi, alfiyyul-anfi mîmiyyul-fammi nûniyyul-ḫâjibi, sam‘uhu yasma‘u sharîral-qalami basharuhu ilas-sab‘ith-thibâqi tsâqibun, qadamâhu qablahumal-ba‘îru fa’azâlâ masy-takâhu minal-miḫani wan-nawâ’ibi, âmana bihidl-dlabbu wa sallamat ‘alaihil-asyjâru wa khâtabathul-aḫjâru wa ḫanna ilaihil-jidz‘u ḫanîna ḫazîn nâdibi, yadâhu tadhharu barakatuhumâ fil-mathâ‘imi wal-masyâribi, qalbuhu lâ yaghfulu wa lâ yanâmu wa lâkin lil-khidmati ‘alad-dawâmi murâqibun, in ûdziya ya‘fu wa lâ yu‘âqibu, wa in khûshima yashmut wa lâ yujâwibu, arfa‘uhu ilâ asyrafil-marâtibi, fî rakbatin lâ tanbaghî qablahu wa lâ ba’dahu lirâkibin, fî maukibi minal-malâ’ikati yafûqu ‘alâ sâ`iril-mawâkibi, faidzar-taqâ ‘alal-kaunaini wanfashala ‘anil-’âlamîna wa washala ilâ qâbi qaisaini kuntu lahu anan-nâdîma wal-mukhâthiba."
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "اَللّٰهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَيْهِ",
                    "latin": "Allâhumma shalli wa sallim wa bârik 'alaihi wa 'alâ âlihi"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Nabi ﷺ diutus oleh Allah di negeri Tihamah (Makkah) di antara saat menjelang datangnya hari kiamat. Pada punggungnya ada tanda kenabian. Apabila berjalan, senantiasa terlindungi awan yang mematuhi perintahnya. Dahinya bercahaya cemerlang, rambutnya bagaikan malam gelap gulita atau hitam pekat. mancung hidungnya bagaikan huruf alif, bulat mulutnya bagaikan huruf mim, lengkung alisnya bagaikan huruf nun. Pendengarannya dapat mendengar geritan pena (di Lauhil Mahfuzh), penglihatannya menembus langit ketujuh. Kedua telapak kakinya dicium unta, maka lenyaplah rasa sakit serta bala’ musibah yang diderita oleh unta itu. Binatang biawak beriman kepadanya, dan pepohonan bersalam kepadanya,, berbicara dengannya batu-batuan, batang kurma meratap kepadanya bagaikan rintihan kesedihan seorang pecinta. Kedua tangannya menampakkan keberkahan pada makanan dan minuman. Hatinya tidak lalai dan tidak pula tidur, tetapi senantiasa mengabdi dan ingat kepada Allah. Bila disakiti, beliau memaafkan dan tidak membalas dendam, Bila dihina, beliau hanya diam dan tidak menjawab, Allah mengangkatnya ke martabat yang paling mulia, Dengan kendaraan yang tak pernah dipakai oleh siapapun, sebelum dan sesudahnya. Bahkan pada derajat golongan malaikat, ketinggian derajatnya melebihi yang lain. Maka ketika Nabi naik melalui dua alam dan berpisah dari dua alam, sampailah ke tempat yang tinggi yang jaraknya sekitar dua busur panah, maka Aku-lah yang menghibur dan berbicara kepadanya."
                    }
                },
                "2": {
                    "text": {
                        "1": "Ya Allah, limpahkan rahmat, kesalamatan, serta keberkahan kepada Nabi Muhammad beserta keluarga beliau"
                    }
                }
            }
        }
    },
    "last_updated": "2024-12-14"
}

=== afaf-tech/sholawat-json/sholawat/diba/nu_online/fasl/21.json
{
    "number": 21,
    "source": "nu-online",
    "name": "",
    "latin": "Fabainamal habîbu…",
    "sections": {
        "1": {
            "name": "",
            "type": "rawi",
            "text": {
                "1": {
                    "arabic": "فَبَيْنَمَا الْحَبِيْبُ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ ذَاتَ يَوْمٍ نَاءٍ عَنِ الْأَوْطَانِ. إِذْ أَقْبَلَ عَلَيْهِ ثَلَاثَةُ نَفَرٍ. كَأَنَّ وُجُوْهَهُمُ الشَّمْسُ وَالْقَمَرُ. فَانْطَلَقَ الصِّبْيَانُ هَرَبًا. وَوَقَفَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ مُتَعَجِّبًا. فَأَضْجَعُوْهُ عَلَى الْأَرْضِ إِضْجَاعًا خَفِيْفًا. وَشَقُّوْا بَطْنَهُ شَقًّا لَطِيْفًا. ثُمَّ أَخْرَجُوا قَلْبَ سَيِّدِ وَلَدِ عَدْنَانَ. وَشَرَّحُوْهُ بِسِكِّيْنِ الْإِحْسَانِ. وَنَزَّعُوْا مِنْهُ حَظَّ الشَّيْطَانِ، وَمَلَؤُهُ بِالْحِلْمِ وَالْعِلْمِ وَالْيَقِيْنِ وَالرِّضْوَانِ. وَأَعَادُوْهُ إِلَى مَكَانِهِ فَقَامَ الْحَبِيْبُ صَلَّى اللهُ عَلَيْهَ وَسَلَّمَ سَوِيًّا كَمَا كَانَ.",
                    "latin": "Fabainamal-ḫabîbu shallallâhu ‘alaihi wa sallama dzâta yaumin nâ’in ‘anil-authâni, idz aqbala ‘alaihi tsalâtsatu nafarin, ka anna wujûhahumusy-syamsu wal-qamaru, fanthalaqash-shibyânu haraban, wa waqafan-nabiyyu shallallâhu ‘alaihi wa sallama muta‘ajjiban, fa adlja‘ûhu ‘alal-ardli idljâ‘an khafîfan, wa syaqqû bathnahu syaqqan lathîfan, tsumma akhrajû qalba sayyidi waladi ‘adnâna, wa syarraḫûhu bisikkînil-iḫsâni, wa nazza‘û minhu ḫadhdhasy-syaithâni, wa mala’uhu bil-ḫilmi wal-‘ilmi wal-yaqîni war-ridlwâni, wa a‘âdûhu ilâ makânihi faqâmal-ḫabîbu shallallâhu ‘alaihi wa sallama sawiyyan kamâ kâna"
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "اَللّٰهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَيْهِ",
                    "latin": "Allâhumma shalli wa sallim wa bârik 'alaihi wa 'alâ âlihi"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Ketika beliau di suatu hari menjauh dari desa, ternyada ada tiga orang mengadap kepada beliau, seakan-akan wajah mereka itu matahari dan rembulan. Maka anak-anak pergi lari dan Nabi ﷺ diam seraya terheran. Lalu mereka membaringkan Nabi di bumi dengan pelan, dan mereka merobek perut beliau dengan lembut, lalu mereka mengeluarkan hati tuan anak Adnan, dan mereka membedah beliau dengan pisau kebagusan, dan mereka menghilangkan dari perut beliau bagian setan, lalu memenuhinya dengan sifat lembut, ilmu, yaqin dan ridlwan, kemudian mereka mengembalikanya ke tempatnya, lalu sang kekasih ﷺ berdiri tegak seperti semula."
                    }
                },
                "2": {
                    "text": {
                        "1": "Ya Allah, limpahkan rahmat, kesalamatan, serta keberkahan kepada Nabi Muhammad beserta keluarga beliau"
                    }
                }
            }
        }
    },
    "last_updated": "2024-12-14"
}

=== afaf-tech/sholawat-json/sholawat/simtudduror/nu_online/fasl/5.json
{
    "number": 5,
    "source": "nu-online",
    "name": "",
    "latin": "Ammâ ba‘du…",
    "sections": {
        "1": {
            "name": "",
            "type": "rawi",
            "text": {
                "1": {
                    "arabic": "أَمَّا بَعْدُ، فَلَمَّا تَعَلَّقَتْ إِرَادَةُ اللهِ فِي الْعِلْمِ الْقَدِيْم. بِظُهُوْرِ أَسْرَارِ التَّخْصِيْصِ لِلْبَشَرِ الْكَرِيْم. بِالتَّقْدِيْمِ وَالتَّكْرِيْمِ. نَفَذَتِ الْقُدْرَةُ الْبَاهِرَة. بِالنِّعْمَةِ الْوَاسِعَةِ وَالْـمِنَّةِ الْغَامِرَة. فَانْفَلَقَتْ بَيْضَةُ التَّصْوِيْر. فِي الْعَالَمِ الْمُطْلَقِ الْكَبِيْر. عَنْ جَمَالٍ مَشْهُوْدٍ بِالْعَيْن. حَاوٍ لِوَصْفِ الْكَمَالِ الْمُطْلَقِ وَالْحُسْنِ التَّامِّ وَالزَّيْن. فَتَنَقَّلَ ذٰلِكَ الْجَمَالُ الْمَيْمُوْن. فِي الْأَصْلَابِ الْكَرِيْمَةِ وَالْبُطُوْن. فَمَا مِنْ صُلْبٍ ضَمَّة. إِلَّا وَتَمَّتْ عَلَيْهِ مِنَ اللهِ النِّعْمَة. فَهُوَ الْقَمَرُ التَّامُّ الَّذِيْ يَتَنَقَّلُ فِي بُرُوْجِهِ. لِيَتَشَرَّفَ بِهِ مَوْطِنُ اسْتِقْرَارِهِ وَمَوْضِعُ خُرُوْجِهِ. وَقَدْ قَضَتِ الْأَقْدَارُ الْأَزَلِيَّةُ بِمَا قَضَتْ وَأَظْهَرَتْ مِنْ سِرِّ هٰذَا النُّوْرِ مَا أَظْهَرَت. وَخَصَّصَتْ بِهِ مَنْ خَصَّصَت. فَكَانَ مُسْتَقَرُّهُ فِي الْأَصْلَابِ الْفَاخِرَة. وَالْأَرْحَامِ الشَّرِيْفَةِ الطَّاهِرَة. حَتَّى بَرَزَ فِي عَالَمِ الشَّهَادَةِ بَشَرًا لَا كَالْبَشَر. وَنُوْرًا حَيَّرَ الْأَفْكَارَ ظُهُوْرُهُ وَبَهَر. فَتَعَلَّقَتْ هِمَّةُ الرَّاقِمِ لِهٰذِهِ الْحُرُوْف. بِأَنْ يَرْقُمَ فِي هٰذَا الْقِرْطَاسِ مَا هُوَ لَدَيْهِ مِنْ عَجَائِبِ ذٰلِكَ النُّوْرِ مَعْرُوْف. وَإِنْ كَانَتِ الْأَلْسُنُ لَا تَفِيْ بِعُشْرِ مِعْشَارِ أَوْصَافِ ذٰلِكَ الْمَوْصُوْف. تَشْوِيْقًا لِلسَّامِعِيْن. مِنْ خَوَاصِّ الْمُؤْمِنِيْن. وَتَرْوِيْحًا لِلْمُتَعَلِّقِيْنَ بِهٰذَا النُّوْرِ الْمُبِيْن. وَإِلَّا فَأَنَّى تُعْرِبُ الْأَقْلَام. عَنْ شُؤُوْنِ خَيْرِ الْأَنَام. وَلٰكِنْ هَزَّنيِ إِلَى تَدْوِيْنِ مَا حَفِظْتُهُ مِنْ سِيَرِ أَشْرَفِ الْمَخْلُوْقِيْن. وَمَا أَكْرَمَهُ اللهُ بِهِ فِي مَوْلِدِهِ مِنَ الْفَضْلِ الَّذِي عَمَّ الْعَالَمِيْن. وَبَقِيَتْ رَايَتُهُ فِي الْكَوْنِ مَنْشُوْرَةً عَلَى مَرِّ الْأَيَّامِ وَالشُّهُوْرِ وَالسِّنِيْن. دَاعِي التَّعَلُّقِ بِهٰذِهِ الْحَضْرَةِ الْكَرِيْمَة. وَلَاعِجُ التَّشَوُّقِ إِلَى سَمَاعِ أَوْصَافِهَا الْعَظِيْمَة. وَلَعَلَّ اللهَ يَنْفَعُ بِهِ الْمُتَكَلِّمَ وَالسَّامِع. فَيَدْخُلَانِ فِي شَفَاعَةِ هٰذَا النَّبِيِّ الشَّافِع. وَيَتَرَوَّحَانِ بِرُوْحِ ذٰلِكَ النَّعِيْ",
                    "latin": "Ammâ ba‘du, falammâ ta‘allaqat irâdatullâhi fil-‘ilmil-qadîmi, bidzuhûri asrârit-takhshîshi lil-basyaril-karîm, bit-taqdîmi wat-takrîmi, nafadatil-qudratul-bâhiratu, bin-ni’matil-wâsi‘ati wal-minnatil-ghâmirati, fanfalaqat baidhatut-tashwîri, fil-‘âlamil-muthlaqil-kabîri, ‘an jamâlin masyhûdin bil-‘aini, ḫâwin liwashfil-kamâlil-muthlaqi wal-ḫusnit-tâmmi waz-zaini, fatanaqqala dzâlikal-jamâlul-maimûn, fil-ashlâbil-karîmati wal-buthûn, famâ min shulbin dhammatin, illâ wa tammat ‘alaihi minallâhin-ni‘mat, fahuwal-qamarut-tâmmul-ladzî yatanaqqalu fî burûjihi, liyatasyarrafa bihi mauthinus-tiqrârihi wa maudli‘u khurûjihi, wa qad qadlatil-aqdârul-azaliyyatu bimâ qadlat wa adhharat min sirri hâdzan-nûri mâ adhharat, wa khashshashat bihi man khashshashat, fakâna mustaqarruhu fil-ashlâbil-fâkhirah, wal-arḫâmisy-syarîfatith-thâhirati, ḫattâ baraza fî ‘âlamisy-syahâdati basyaran lâ kal-basyari, wa nûran ḫayyaral-afkâra dhuhûruhu wa bahar. fata’allaqat himmatur-râqimi lihâdzihil-ḫurûf, bi an yarquma fî hâdzal-qirthâsi mâ huwa ladaihi min ‘ajâ’ibi dzâlikan-nûri ma‘rûfi, wa in kânatil-alsunu lâ tafî bi‘usyri mi‘syâri aushâfi dzâlikal-maushûfi, tasywîqan lis-sâmi‘în, min khawashshil-mu’minîn. watarwîḫan lil-muta‘alliqîna bihâdzan-nûril-mubîn, wa illâ fa annâ tu‘ribul-aqlâm, ‘an syu’ûni khairil-anâm, wa lâkin hazzanî ilâ tadwîni mâ ḫafidhtuhu min siyari asyrafil-makhlûqîn. wa mâ akramahullâhu bihi fî maulidihi minal-fadllil-ladzî ‘ammal-‘âlamîn, wa baqiyat râyatuhu fil-kauni mansyûratan ‘alâ marril-ayyâmi wash-syuhûri was-sinîn. dâ‘iyat-ta‘alluqi bihâdzihil-ḫadlratil-karîmati, wa lâ ‘ijut-tasyawwuqi ilâ samâ’i aushâfihâl-‘adhîmati, wa la‘allallâhu yanfa‘u bihil-mutakallima was-sâmi‘, fayadkhulâni fî syafâ‘ati hâdzan-nabiyyisy-syâfi‘ wayatarawwaḫâni birûḫi dzâlikan-na‘îm."
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "﴿اَللّٰهُمَّ صَلِّ وَسَلِّمْ أَشْرَفَ الصَّلَاةِ وَالتَّسْلِيْمِ عَلَى سَيِّدِنَا وَنَبِيِّنَا مُحَمَّدٍ ࣙالرَّؤُوْفِ الرَّحِيْمِ﴾"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Amma ba’du. Manakala iradat Allah dalam ilmu-Nya yang qadim. Berkenan menampakkan inti kekhususan, bagi manusia yang mulia. Dengan keutamaan dan penghormatan. Terwujudlah dengan kodrat gemilang. Nikmat llahiyang luas merata. Serta anugerah-Nya yang melimpah ruah. Maka terkuaklah karsa cipta-Nya. Di alam mutlak tiada berbatas. Menyingkap “keindahan” disaksikan pandangan mata. Mencakup segala sifat keindahan dan keelokan sempurna. Dan berpindah-pindahlah ia dengan segala keberkahan. Dalam sulbi-sulbi dan rahim-rahim yang mulia. Tiada satu pun sulbi yang merangkumnya. Kecuali beroleh nikmat Allah nan sempurna. Laksana bulan purnama. Berpindah-pindah dalam orbitnya. Agar setiap tempat yang didiaminya. Ataupun jalan yang dilaluinya. Meraih kemuliaan tiada terhingga. Demikianlah ditetapkan dalam suratan takdir azali. Menampakkan rahasia nur ini. Hanya dalam diri mereka. Yang beroleh kekhususan dan keistimewaan. Sehingga tiap kediamannya. Selalu dalam sulbi-sulbi megah dan anggun. Serta rahim-rahim yang suci bersih. Sampai tiba saat ia datang ke alam nyata. Sebagai manusia, tiada sama dengan manusia biasa. Bagaikan nur cahaya benderang. Penampilannya mencengangkan akal dan pikiran. Maka tergeraklah jiwa dan semangat penulis ini. Mencatat apa yang sampai kepadanya. Tentang keajaiban nur mulia ini. Meski lidah tak’kan mampu mengungkap sifat-sifatnya walaupun sekelumit atau lebih sedikit. Tapi sekadar penawar hati para pendengar. Yang termasuk kalangan khusus di antara kaum mukminim. Dan penghibur mereka yang terpaut hatinya. Pada pesona nur Yang terang ini. Sebab bagaimana mungkin. Pena para penulis mampu melukis. Tentang segala sesuatu yang bersangkutan. Dengan manusia Paling utama. Di antara manusia seluruhnYa. Namun hatiku tergerak. Menuliskan yang kuhafal selama ini. Tentang riwayat hidup manusia termulia. Di antara makhluk semuanya. Juga tentang karunia agung yang dilimpahkan Allah. Pada peristiwa kelahirannya. Yang meliputi seluruh penghuni alam semesta. Dan panji-panjinya yang berkibar megah. Di segenap penjuru jagat raya. Terus-menerus sepanjang pergantian hari, bulan, dan tahun. Semuanya itu didorong semata-mata. Oleh kegandrunganku pada pribadi luhur ini. Serta kerinduanku ‘tuk mendengarkan selalu. Sebutan sifat-sifatnya yang serba agung. Dan kiranya Allah berkenan melipatgandakan manfaatnya. Bagi si pembicara ataupun pendengarnya. Sehingga keduanya’kan memasuki pintu syafa’at. Dan menghirup sejuknya kenikmatan itu."
                    }
                }
            }
        }
    },
    "last_updated": "2024-11-16"
}

=== afaf-tech/sholawat-json/sholawat/diba/nu_online/fasl/16.json
{
    "number": 16,
    "source": "nu-online",
    "name": "",
    "latin": "Fahtazzal arsyu…",
    "sections": {
        "1": {
            "name": "",
            "type": "rawi",
            "text": {
                "1": {
                    "arabic": "فَاهْتَزَّ الْعَرْشُ طَرَبًا وَاسْتِبْشَارًا. وَازْدَادَ الْكُرْسِيُّ هَيْبَةً وَوَقَارًا. وَامْتَلَأَتِ السَّمٰوَاتُ أَنْوَارًا. وَضَجَّتِ الْمَلَآئِكَةُ تَهْلِيْلًا وَتَمْجِيْدًا وَاسْتِغْفَارًا. ﴿سُبْحَانَ الله وَالْحَمْدُ ِللّٰهِ وَلَآإِلٰهَ إِلَّا اللهُ وَاللهُ أَكْبَرُ ×٣﴾. وَلَمْ تَزَلْ أمُّهٗ تَرٰى أَنْوَاعًا مِنْ فَخْرِهِ وَفَضْلِهِ. إِلَى نِهَايَةِ تَمَامِ حَمْلِهِ. فَلَمَّا اشْتَدَّ بِهَا الطَّلْقُ. بِـإِذْنِ رَبِّ الْخَلْقِ. وَضَعَتِ الْحَبِيْبَ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ. سَاجِدًا شَاكِـرًا حَامِدًا كَأَنَّهُ الْبَدْرُ فِيْ تَمَامِهِ.",
                    "latin": "Fahtazzal-‘arsyu tharaban wastibsyâran, wazdâdal-kursiyyu haibatan wa waqâran, wamtala'atis-samâwâtu anwâran, wadlajjatil-malâ'ikatu tahlîlan wa tamjîdan was-tighfâran. ﴾subḫânallâh wal-ḫamdu lillâhi wa lâ ilâha illallâhu wallâhu akbar 3x﴿ wa lam tazal ummuhu tarâ anwâ‘an min fakhrihi wa fadllihi, ilâ nihâyati tamâmi ḫamlihi, falammasy-tada bihath-thalqu, bi idzni rabbil-khalqi, wa dla‘atil-ḫabîba shallallâhu ‘alaihi wa sallama, sâjidan syâkiran ḫâmidan ka annahul-badru fî tamâmihi."
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "اَللّٰهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَيْهِ",
                    "latin": "Allâhumma shalli wa sallim wa bârik 'alaihi wa 'alâ âlihi"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Maka berguncanglah ‘Arsy penuh suka cita dan riang gembira. Dan Kursi Allah bertambah wibawa dan tenang karena memuliakannya. Dan langit penuh dengan cahaya, serta bergemuruh suara malaikat membaca tahlil, tamjid dan istighfar. (Mahasuci Allah, limpahan puji bagi Allah, tiada Tuhan selain Allah, dialah Allah yang Mahabesar (3x). Dan ibunya tiada henti-hentinya melihat bermacam-macam keajaiban dari keistimewaan dan keutamaan janin hingga sempurna masa kandungannya, Maka ketika ibunya telah merasakan sakit karena kandungannya akan lahir, dengan izin Tuhannya, Tuhan Pencipta makhluk, Lahirlah kekasih Allah Muhammad ﷺ dalam keadaan sujud, bersyukur dan memuji, sedangkan wajahnya bagaikan sempurnanya bulan purnama. "
                    }
                },
                "2": {
                    "text": {
                        "1": "Ya Allah, limpahkan rahmat, kesalamatan, serta keberkahan kepada Nabi Muhammad beserta keluarga beliau"
                    }
                }
            }
        }
    },
    "last_updated": "2024-12-14"
}
