=== afaf-tech/sholawat-json/schemas/diba_fasl_v1.0.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Diba Fasl Schema",
    "version": "1.0",
    "type": "object",
    "properties": {
        "number": {
            "type": "integer",
            "minimum": 1,
            "description": "The chapter number."
        },
        "source": {
            "type": "string",
            "description": "The source of the text."
        },
        "name": {
            "type": "string",
            "description": "The Arabic name of the fasl (chapter)."
        },
        "latin": {
            "type": [
                "string",
                "null"
            ],
            "description": "The transliteration of the chapter name."
        },
        "sections": {
            "type": "object",
            "patternProperties": {
                "^[0-9]+$": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string",
                            "enum": [
                                "rawi",
                                "bari",
                                "closing"
                            ]
                        },
                        "text": {
                            "type": "object",
                            "patternProperties": {
                                "^[0-9]+$": {
                                    "type": "object",
                                    "properties": {
                                        "arabic": {
                                            "type": "string",
                                            "description": "The Arabic text of the verse."
                                        },
                                        "latin": {
                                            "type": [
                                                "string",
                                                "null"
                                            ],
                                            "description": "The transliteration of the Arabic text."
                                        }
                                    },
                                    "required": [
                                        "arabic"
                                    ]
                                }
                            },
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "type",
                        "text"
                    ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "translations": {
            "type": "object",
            "description": "Translations in various languages.",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "muqaddimah": {
                            "type": "string",
                            "description": "(introduction) of the chapter."
                        },
                        "translator": {
                            "type": "string",
                            "description": "translator of the chapter."
                        },
                        "sections": {
                            "type": "object",
                            "patternProperties": {
                                "^[0-9]+$": {
                                    "type": "object",
                                    "properties": {
                                        "text": {
                                            "type": "object",
                                            "patternProperties": {
                                                "^[0-9]+$": {
                                                    "type": "string"
                                                }
                                            },
                                            "additionalProperties": false
                                        }
                                    },
                                    "required": [
                                        "text"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "sections"
                    ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "last_updated": {
            "type": "string",
            "format": "date",
            "pattern": "^(\\d{4})-(\\d{2})-(\\d{2})$",
            "description": "The date when the data was last updated, in ISO 8601 date format (e.g., '2024-11-09')."
        }
    },
    "required": [
        "number",
        "source",
        "name",
        "last_updated"
    ],
    "anyOf": [
        {
            "required": [
                "sections"
            ]
        },
        {
            "required": [
                "translations"
            ]
        }
    ],
    "additionalProperties": false
}

=== afaf-tech/sholawat-json/sholawat/diba/nu_online/fasl/12.json
{
    "number": 12,
    "source": "nu-online",
    "name": "",
    "latin": "Al-ḫadîtsul awwal…",
    "sections": {
        "1": {
            "name": "",
            "type": "rawi",
            "text": {
                "1": {
                    "arabic": "اَلْحَدِيْثُ الْأَوَّلُ عَنْ بَحْرِ الْعِلْمِ الدَّافِقِ. وَلِسَانِ الْقُرْآَنِ النَّاطِقِ. أَوْحَدِ عُلَمَآءِ النَّاسِ. سَيِّدِنَا عَبْدِ اللهِ بْنِ سَيِّدِنَا الْعَبَّاسِ رَضِيَ اللهُ عَنْهُمَا، أَنَّ رَسُوْلَ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ أَنَّهٗ قَالَ: إِنَّ قُرَيْشًا كَانَتْ نُوْرًا بَيْنَ يَدَيِ اللهِ عَزَّ وَجَلَّ قَبْلَ أَنْ يَّخْلُقَ اٰدَمَ بِأَلْفَيْ عَامٍ يُسَبِّحُ اللهَ ذٰلِكَ النُّوْرُ وَتُسَبِّحُ الْمَلَآئِكَةُ بِتَسْبِيْحِهٖ. فَلَمَّا خَلَقَ اللهُ اٰدَمَ أَوْدَعَ ذٰلِكَ النُّوْرَ فِيْ طِيْنَتِهٖ. قَالَ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ: فَأَهْبَطَنِيَ اللهُ عَزَّ وَجَلَّ إِلَى الْأَرْضِ فِيْ ظَهْرِ اٰدَمَ. وَحَمَلَنِيْ فِي السَّفِيْنَةِ فِيْ صُلْبِ نُوْحٍ وَّجَعَلَنِيْ فِيْ صُلْبِ الْخَلِيْلِ إِبْرَاهِيْمَ حِيْنَ قُذِفَ بِهٖ فِي النَّارِ. وَلَمْ يَزَلِ اللهُ عَزَّ وَجَلَّ يُنَقِّلُنِيْ مِنَ الْأَصْلَابِ الطَّاهِرَةِ. إِلَى الْأَرْحَامِ الزَّكِيَّةِ الْفَاخِرَةِ. حَتّٰى أَخْرَجَنِيَ اللهُ مِنْ بَيْنِ أَبَوَيَّ وَهُمَا لَمْ يَلْتَقِيَا عَلَى سِفَاحٍ قَطُّ",
                    "latin": "Al-hadîtsul-awwalu ‘an baḫril-‘ilmid-dâfiqi, wa lisânin-nâthiqi, au ḫadi ‘ulamâ`in-nâsi,sayyidininâ ‘abdillâhib-ni sayyidinâl-‘abbâsi radliyyallâhu ‘anhumâ, anna rasûlallâhi shallallâhu ‘alaihi wa sallama annahu qâla: inna quraisyan kânat nûran baina yadayillâhi ‘azza wa jalla qabla an yakhluqa âdama bi alfai ‘âmin yusabbiḫuallâa dzâlikan-nûru wa tasabbiḫul-malâ`ikatu batasbîḫihi, falammâ khalaqallâhu âdama auda’a dzâlikan-nûru fî thînatihi, qâla shallallâhu ‘alaihi wa sallama: fa`ahbathaniyallâhu ‘azza wa jalla ilal-ardli fî dhahri âdama, wa ḫamalanî fis-safînati fî shulbi nûḫi wa ja’alanî fî shulbil-khalîli ibrâhîma ḫîna qudzifa bihî fin-nâri, wa lam yazalillâhu ‘azza wa jalla yunaqqilunî minal-ashlâbith-thâhirati, ilal-arḫâmiz-zakiyyatil-fâkhirati, ḫattâ akhrajaniyallâhu min baini abawayya wa humâ lam yaltaqiyâ ‘alâ sifâḫin qaththu."
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "اَللّٰهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَيْهِ",
                    "latin": "Allâhumma shalli wa sallim wa bârik 'alaihi wa 'alâ âlihi"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Hadits pertama dari pancaran seseorang yang ilmunya seluas samudra, tutur katanya dengan bahasa Al-Qur’an dan salah seorang ulama terkenal pada masanya, yaitu Sayyidina Abdulloh bin Sayyidina Abbas rodhiyallahu ‘anhumaa dari Rasulullah ﷺ bahwasanya beliau telah bersabda: Sesungguhnya ada seorang Quraisy (Nabi Muhammad ﷺ) yang ketika itu masih berwujud nur (cahaya) di hadapan Allah Yang Maha Perkasa dan Maha Agung, sebelum Allah menciptakan Nabi Adam kira-kira dua ribu tahun, Nur itu selalu bertasbih kepada Allah dan bertasbih pula para malaikat mengikuti bacaan tasbihnya. Ketika Allah menciptakan Nabi Adam, maka nur itu diletakkan pada tanah liat asal kejadian Nabi Adam. Nabi ﷺ bersabda: Lalu Allah Yang Maha Perkasa dan Maha Agung menurunkan nur itu ke bumi melalui punggung Nabi Adam dan membawaku ke dalam kapal, dan menjadikan aku dalam tulang rusuk sang kekasih, yakni Nabi lbrohim ketika dilempar ke dalam api. Tiada henti-hentinya Allah Yang Maha Perkasa dan Maha Agung memindahkan aku dari beberapa tulang rusuk yang suci, sampai pada rahim yang suci dan megah, hingga Allah melahirkan aku melalui kedua orang tuaku, dan keduanya tidak pernah berbuat zina sama sekali."
                    }
                },
                "2": {
                    "text": {
                        "1": "Ya Allah, limpahkan rahmat, kesalamatan, serta keberkahan kepada Nabi Muhammad beserta keluarga beliau"
                    }
                }
            }
        }
    },
    "last_updated": "2024-12-14"
}

=== afaf-tech/sholawat-json/sholawat/diba/nu_online/fasl/9.json
{
    "number": 9,
    "source": "nu-online",
    "name": "",
    "latin": "Shalâtullâhi ma laḫat…",
    "sections": {
        "1": {
            "name": "",
            "type": "bari",
            "text": {
                "1": {
                    "arabic": "صَــــلَاةُ اللهِ مَـــا لَاحَتْ كَوَاكِبْ ۞ عَلَى احْمَدْ خَيْرِ مَنْ رَّكِبَ النَّجَآئِبْ",
                    "latin": "Shalâtullâhi mâ lâḫat kawâkib ۞ ‘ala aḫmad khairi man rakiban-najâ’ib"
                },
                "2": {
                    "arabic": "حَدٰى حَادِى السُّرٰى بِاسْمِ الْحَبَائِبْ ۞ فَهَـــــزَّ الشُّكْرُ أَعْطَافَ الرَّكَائِبْ",
                    "latin": "ḫadâ hâdis-surâ bismil-ḫabâ’ib ۞ fahazzasy-syukru a‘thâfur-rakâ’ib"
                },
                "3": {
                    "arabic": "أَلَمْ تَرَهَا وَقَدْ مَدَّتْ حُـــطَاهَـــا ۞ وَسَالَتْ مِنْ مَّدَامِعِـــهَا سَحَـــآئِبْ",
                    "latin": "Alam tarahâ wa qad madat ḫuthâhâ ۞ wa sâlat min madâmi‘ihâ saḫâ’ib"
                },
                "4": {
                    "arabic": "وَمَالَتْ لِلْـــحِمٰى طَرَبًا وَحَنَّتْ ۞ إِلَى تِلْكَ الْمَعَالِمِ وَالْمَــــلَاعِبْ",
                    "latin": "Wa mâ lilḫimâ tharaban wa ḫannat ۞ ilâ tilkal-ma‘âlimi wal-malâ‘ib"
                },
                "5": {
                    "arabic": "فَدَعْ جَذْبَ الزِّمَامِ وَلَا تَسُـقْهَا ۞ فَقَائِدُ شَوقِهَا لِلْــــحَيِّ جَـــاذِبْ",
                    "latin": "Fada‘ jadzbaz-zimâmi wa lâ tasuqhâ ۞ faqâ’idu syauqihâ lil-ḫayyi jâdzib"
                },
                "6": {
                    "arabic": "فَهِمْ طَــــرَبًا كَمَا هَــــامَتْ وَإِلَّا ۞ فَإِنَّكَ فِي طَـــرِيقِ الْحُـبِّ كَاذِبْ",
                    "latin": "Fahim tharaban kamâ hamat wa illâ ۞ fa innaka fî tharîqil-ḫubbi kâdzib"
                },
                "7": {
                    "arabic": "أَمَّا هٰذَا الْعَقِيْــــقُ بَدَا وَهٰذِيْ ۞ قِبَابُ الْحَيِّ لَاحَتْ وَالْمَــضَارِبْ",
                    "latin": "Ammâ hâdzal-‘aqîqu badâ wa hâdzî ۞ qibâbul-ḫayyi lâḫat wal-madlârib"
                },
                "8": {
                    "arabic": "وَتِلْكَ الْقُبَّــــةُ الْخَــضْرَا وَفِيْهَــــا ۞ نَبِيٌّ نُوْرُهٗ يَجْـــلُوْ الْغَـــيَاهِبْ",
                    "latin": "Wa tilkal-qubbatul-khadlrâ wa fîhâ ۞nabiyyun nûruhu yajlul-ghayâhib"
                },
                "9": {
                    "arabic": "وَقَـدْ صَحَّ الرِّضَى وَدَنَا التَّلَاقِي ۞ وَقَدْ جَاءَ الْهَنَا مِنْ كُلِّ جَــــانِبْ",
                    "latin": "Wa qad shaḫḫar-ridlâ wa danat-talâqî ۞ wa qad jâ’al-hanâ min kulli jânib"
                },
                "10": {
                    "arabic": "فَقُلْ لِّلنَّفْسِ دُوْنَكِ وَالتَّمَــلِّى ۞ فَمَا دُوْنَ الْحَبِيْبِ الْيَوْمَ حَــــاجِبْ",
                    "latin": "Faqul linnafsi dûnaki wat-tamallî ۞ famâ dûnal-ḫabîbil-yauma ḫâjib"
                },
                "11": {
                    "arabic": "تَمَلَّى بِـــالْحَبِيْبِ بِكُلِّ قَصْـــــدٍ ۞ فَقَدْ حَصَلَ الْهَنَا وَالضِـــدُّ غَائِبْ",
                    "latin": "Tamallâ bil-ḫabîbi bikulli qashdin ۞ faqad hashalal-hanâ wadl-dliddu ghâ’ib"
                },
                "12": {
                    "arabic": "نَبِيُّ اللهِ خَــــيْرُ الْخَلْقِ جَمْـعًـــــا ۞ لَهٗ أَعْلَى الْمَنَاصِبِ وَالْمَـــرَاتِبْ",
                    "latin": "Nabiyyullâhi Khairul-khalqi jam‘a ۞ lahu a‘lal-manâshibi wal-marâtib"
                },
                "13": {
                    "arabic": "لَهُ الْجَاهُ الرَّفِيْــــعُ لَهُ الْمَعَـــالِي ۞ لَهُ الشَّرَفُ الْمُؤَبَّدُ وَالْمَنَـــاقِبْ",
                    "latin": "Lahul-jâhur-râfi‘u lahul-ma‘âlî ۞ lahusy-syaraful-mu’abbadu wal-manâqib"
                },
                "14": {
                    "arabic": "فَـــلَوْ أَنَّـــــا سَعَيْنَــا كُلَّ يَومٍ ۞ عَلَى الْأَحْدَاقِ لَا فَوْقَ النَّجَــــائِبْ",
                    "latin": "Falau annâ sa‘ainâ kulla yaumin ۞ ‘alal-aḫdâqi lâ fauqan-najâ’ib"
                },
                "15": {
                    "arabic": "وَلَوْ أَنَّــا عَمِلْنَــــا كُلَّ حِــــيْنٍ ۞ لِأَحْمَـــدَ مَوْلِدًا قَــدْ كَانَ وَاجِبْ",
                    "latin": "Wa lau annâ ‘amilnâ kulla ḫînin ۞ li aḫmada maulidin qad kâna wâjib"
                },
                "16": {
                    "arabic": "عَلَيْهِ مِنَ الْمُهَيْمِنِ كُلَّ وَقْتٍ ۞ صَلَاةٌ مَّا بَدَا نُورُ الْكَواكِبْ",
                    "latin": "‘alaihi minal-muhaimini kulla waqtin ۞ shalâtun mâ badâ nûrul-kawâkib"
                },
                "17": {
                    "arabic": "تَعُـــمُّ الْاٰلَ وَالْأَصْحَـابَ طُرًّا ۞ جَمِيعَهُــــــمْ وَعِتْرَتَـــــهُ الْأَطَايِبْ",
                    "latin": "Ta‘ummul-âla wal-ashḫâba thurran ۞ jamî‘ahum wa ‘itratahul-athâyib"
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "اَللّٰهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَيْهِ",
                    "latin": "Allâhumma shalli wa sallim wa bârik 'alaihi wa 'alâ âlihi"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Selagi cahaya bintang masih gemerlapan, semoga rahmat Allah tercurah. Kepada Nabi Muhammad, Sang pengendara unta terbaik",
                        "2": "Pengiring unta berdendang menyanyikan lagu menyebut nama kekasih. Sementara untanya mengangguk-angguk menari gembira mengikuti irama lagu penunggangnya",
                        "3": "Tidakkah engkau lihat, semakin cepat langkah unta? Bercucuran deras dari matanya air mata bagaikan awan tiba.",
                        "4": "Semakin condong langkahnya karena kegembiraan dan rindu Menuju kandang dan ladang penggembalaannya.",
                        "5": "Biarkan, jangan kau Tarik tali kekang dan jangan menggiringnya. Karena kerinduan pada sang nabilah yang akan menariknya.",
                        "6": "Tunjukkanlah rasa cintamu sebagaimana cintanya unta dan jikalau tidak, Maka jalan cintamu pada nabi adalah dusta.",
                        "7": "Perhatikan, kota Aqiq telah nampak dan inilah Kubah-kubah penduduk, gemerlapan cahayanya menyilaukan",
                        "8": "Dan itulah kubah hijau dan di dalamnya, Terdapar seorang Nabi yang nur-nya menerangi kegelapan.",
                        "9": "Dan sungguh jelas keridhaan Allah seiring pertemuan yang semakin dekat Dan sungguh telah datang kegembiraan dari segala penjuru.",
                        "10": "Maka bisikkan ke dalam hati, “temui sang kekasih dan bergembiralah”. Maka hari ini tiada satupun yang menjadi penghalang kepada kekasih",
                        "11": "Condongkanlah rasa cinta kepada kekasih di segala tujuan, Maka pastilah akan datang suka dan lenyaplah duka.",
                        "12": "Nabi Allah adalah sebaik-baiknya seluruh makhluk. Baginya keluhuran pangkat dan martabat tertinggi.",
                        "13": "Baginya kedudukan yang tinggi serta segala keluhuran. Kemuliaannya diabadikan dan menjadi kenangan.",
                        "14": "Maka seandainya kami menuju tempat, berjalan setiap saat Di atas pandangan, bukan di punggung-punggung unta.",
                        "15": "Dan seandainya kami beramal setiap hari Pada peringatan kelahiran Ahmad, maka sungguh hukumnya wajib.",
                        "16": "Setiap waktu kumohonkan untuknya dari Allah. Rahmat selama bintang-bintang masih bercahaya.",
                        "17": "Yang merata kepada keluarga dan para sahabat semuanya. Serta semua keturunannya yang baik-baik lagi mulia."
                    }
                },
                "2": {
                    "text": {
                        "1": "Ya Allah, limpahkan rahmat, kesalamatan, serta keberkahan kepada Nabi Muhammad beserta keluarga beliau"
                    }
                }
            }
        }
    },
    "last_updated": "2024-12-14"
}

=== afaf-tech/sholawat-json/sholawat/diba/nu_online/fasl/13.json
{
    "number": 13,
    "source": "nu-online",
    "name": "",
    "latin": "Al-hadîtsuts tsânî…",
    "sections": {
        "1": {
            "name": "",
            "type": "rawi",
            "text": {
                "1": {
                    "arabic": "اَلْحَدِيْثُ الثَّانِيُّ عَنْ عَطَاءِ بْنِ يَسَارٍ. عَنْ كَعْبِ الْأَحْبَارِ. قَالَ: عَلَّمَنِيْ أَبِيْ التَّوْرَاةَ إِلَّا سِفْرًا وَاحِدًا كَانَ يَخْتِمُهٗ وَيُدْخِلُهُ الصُّنْدُوْقَ. فَلَمَّا مَاتَ أَبِيْ فَتَحْتُهٗ فَإِذًا فِيْهِ نَبِيٌّ يَخْرُجُ اٰخِرَ الزَّمَانِ. مَوْلِدُهٗ بِمَكَّةَ. وَهِجْرَتُهٗ بِالْمَدِيْنَةِ. وَسُلْطَانُهٗ بِالشَّامِ. يَقُصُّ شَعْرَهٗ وَيَتَّزِرُ عَلَى وَسَطِهِ. يَكُوْنُ خَيْرَ اْلأَنْبِيَآءِ وَأُمَّتُهٗ خَيْرَ الْأُمَمِ. يُكَّبِرُوْنَ اللهَ تَعَالٰى عَلَى كُلِّ شَرَفٍ. يَصُفُّوْنَ فِي الصَّلاَةِ كَصُفُوْفِهِمْ فِي الْقِتَالِ. قُلُوْبُهُمْ مَصَاحِفُهُمْ يَحْمَدُوْنَ اللهَ تَعَالىٰ عَلَى كُلِّ شِدَّةٍ وَّرَخَآءٍ. ثُلُثٌ يَّدْخُلُوْنَ الْجَنَّةَ بِغَيْرِ حِسَابٍ. وَثُلُثٌ يَّأْتُوْنَ بِذُنُوْبِهِمْ وَخَطَايَاهُمْ فَيُغْفَرُ لَهُمْ. وَثُلُثٌ يَّأْتُوْنَ بِذُنُوْبٍ وَخَطَايَا عِظَامٍ. فَيَقُوْلُ اللهُ تَعَالىٰ لِلْمَلَآئِكَةِ ٱذْهَبُوْا وَزِنُوْهُمْ فَيَقُوْلُوْنَ يَا رَبَّنَا وَجَدْنَاهُمْ أَسْرَفُوْا عَلَى أَنْفُسِهِمْ وَوَجَدْنَا أَعْمَالَهُمْ مِّنَ الذُّنُوْبِ كَأَمْثَالِ الْجِبَالِ. غَيْرَ أَنَّهُمْ يَشْهَدُوْنَ أَنْ لَآ إِلٰهَ إِلَّا اللهُ. وَأَنَّ مُحَمَّدًا رَّسُوْلُ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ",
                    "latin": "Al-ḫaditsuts-tsânîyyu ‘an ‘athâ`ib-ni yasârin, ‘an ka’binl-aḫbâr, qâla: ‘allamanî abit-taurâta illâ sifran wâḫidan kâna yakhtimuhu wa yudkhiluhush-shundûqa, falammâ mâta abî fataḫtuhu fa idzan fîhi nabiyyun yakhruju âkhiraz-zamâni, mauliduhu bimakkata, wa hijratuhu bil-madînati, wa sulthânuhu bisy-syâmi, yaqushshu sya’rahu wa yattaziru ‘alâ wasathihi, yakûnu khairal-anbiyâ`i wa ummatuhu khairal-umami, yukabbirûnallâha ta’âlâ ‘alâ kulli syarafin, yashuffûna fish-shalâti kashufûfihim fil-qitâli, qulûbuhum mashâḫifuhum yaḫmadûnallâha ta’âlâ ‘alâ kulli syiddatin wa rakhâ`in, tsulutsun yadkhulûnal-jannata bighairi ḫisâbin, wa tsulutsun ya`tuna bidzunûbihim wa khathâyâhum fayughfaru lahum, wa tsulutsun ya`tuna bidzunûbihim wa khthâyâhum fayughfaru lahum, wa tsulutsun ya`tuna bidzunûbin wa khathâyâ ‘idhâmin, fayaqûlullâhu ta’alâ lil-malâ`ikatidz-habû wazinûhum fayaqûlûna yâ rabbanâ wajadnâhum asrafû ‘alâ anfusihim wawajadnâ a’mâlahum mindz-dzunûbi ka`amtsâlil-jibâli, ghaira annahum yashhadûna an lâ ilâha illallâhu, wa anna muḫammadn rasûlullâhi shallallâhu ‘alaihi wa sallama."
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "اَللّٰهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَيْهِ",
                    "latin": "Allâhumma shalli wa sallim wa bârik 'alaihi wa 'alâ âlihi"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Hadits kedua riwayat dari ‘Atho bin Yasar dari Ka’ab Al-Ahbar telah berkata: Ayahku telah mengajarkan kepadaku kitab Taurat hingga tamat, kecuali selembar saja yang tidak diajarkan dan memasukkannya ke dalam peti. Maka setelah ayahku meninggal, aku membuka peti itu, ternyata selembar kitab Taurat tadi menerangkan tentang akan Iahirnya nabi akhir zaman, yang tempat kelahirannya di kota Makkah dan dan hijrah ke Madinah serta kekuasaannya meluas ke negeri Syam. Beliau mencukur rambutnya dan berkain pada pinggangnya. Beliau adalah sebaik-baiknya para nabi, dan umatnya juga sebaik-baik umat. Mereka bertakbir mengagungkan kebesaran Allah Yang Mahatinggi atas segala kemuliaan. Mereka berbaris pada waktu shalat sebagaimana barisan mereka di dalam peperangan. Hati mereka adalah kitab sucinya. Mereka selalu memuji Allah dalam keadaan suka dan duka. Sepertiga dari mereka masuk surga tanpa dihisab, sepertiga lagi datang dengan dosa-dosanya, lalu diampuni. Dan yang sepertiga lainnya datang dengan dosa-dosa dan kesalahan-kesalahan besar. Maka Allah Ta’ala berfirman kepada malaikat: Pergilah dan timbanglah amal perbuatan mereka. Lalu para malaikat berkata: Wahai Tuhan kami, telah kami dapatkan mereka melampaui batas dalam menyia-nyiakan dirinya sendiri, dan kami dapatkan amal-amal mereka penuh dari dosa-dosa bagaikan besarnya gunung-gunung. Pada sisi lainnya mereka sungguh bersaksi bahwa tiada Tuhan melainkan Allah dan sesungguhnya Nabi Muhammad ﷺ itu adalah utusan Allah."
                    }
                },
                "2": {
                    "text": {
                        "1": "Ya Allah, limpahkan rahmat, kesalamatan, serta keberkahan kepada Nabi Muhammad beserta keluarga beliau"
                    }
                }
            }
        }
    },
    "last_updated": "2024-12-14"
}

=== afaf-tech/sholawat-json/sholawat/diba/nu_online/fasl/28.json
{
    "number": 28,
    "source": "nu-online",
    "name": "",
    "latin": "Ya badratimmin…",
    "sections": {
        "1": {
            "name": "",
            "type": "bari",
            "text": {
                "1": {
                    "arabic": "يَا بَــــدْرَتِمٍّ حَــــازَ کُلَّ كَمَالِ ۞ مَــــاذَا يُعَبِّرُعَنْ عُلَاكَ مَقَــــالِي",
                    "latin": "Ya badratimin hâza kulla kamâli ۞ mâ dzâ yu‘abbiru ‘an ‘ulâka maqâlî"
                },
                "2": {
                    "arabic": "أَنْتَ الَّذِی أَشْرَقْتَ فِي أُفُقِ الْعُلَا ۞ فَمَــحَوْتَ بِالْأَنْوارِکُلَّ ضَــــلَالِ",
                    "latin": "Antal-ladzî asyraqta fî ufuqil-‘ulâ ۞ famaḫauta bil-anwâri kulla dlalâli"
                },
                "3": {
                    "arabic": "وَبِكَ اسْتَنَارَ الْكَوْنُ يَا عَلَمَ الْهُدٰى ۞ بِالنُّورِ وَالْإِنْعَــــامِ وَالْإِفْضَالِ",
                    "latin": "Wa bikas-tanâral-kaunu yâ ‘alamal-hudâ ۞ bin-nûri wal-in‘âmi wal-ifdlâli"
                },
                "4": {
                    "arabic": "صَــــــلَّى عَلَيْــــكَ اللهُ رَبِّي دَاِئمًــــــا ۞ أَبَدًا مَــــعَ الْإِبْكاَرِ وَالْاٰصَــــالِ",
                    "latin": "Shalla ‘alaikallâhu rabbi dâ'imân ۞ abadan ma‘al-ibkâri wal-âshâli"
                },
                "5": {
                    "arabic": "وَعَلَى جَمِيْعِ الْآلِ وَالْأَصْحَابِ مَنْ ۞ قَدْ خَصَّهُمْ رَبُّ العُلَى بِكَمَالِ",
                    "latin": "Wa ‘alâ jamî‘il-âli wal-ashḫâbi man ۞ qad khashshahum rabbul-‘ulâ bikamâli"
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "اَللّٰهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَيْهِ",
                    "latin": "Allâhumma shalli wa sallim wa bârik 'alaihi wa 'alâ âlihi"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Wahai purnama kesempurnaan yang telah mencapai puncak kesempurnaan. Ungkapan apa yang dapat aku katakan untuk menguraikan keluhuranmu.",
                        "2": "Engkaulah yang terbit di ufuk ketinggian, dengan cahayamu engkau lenyapkan kesesatan",
                        "3": "Dengan kehadiranmu semesta raya menjadi terang benderang wahai Sumber petunjuk, dengan cahaya, kenikmatan, serta keutamaanmu.",
                        "4": "Semoga rahmat Allah, Tuhanku, senantiasa dilimpahkan kepadamu, kekal sepanjang masa, setiap pagi dan sore hari.",
                        "5": "Juga kepada segenap keluarga dan para sahabat, yaitu orang-orang yang benar-benar telah diistimewakan Tuhan, Yang Mahatinggi, dengan kesempurnaan"
                    }
                },
                "2": {
                    "text": {
                        "1": "Ya Allah, limpahkan rahmat, kesalamatan, serta keberkahan kepada Nabi Muhammad beserta keluarga beliau"
                    }
                }
            }
        }
    },
    "last_updated": "2024-12-12"
}

=== afaf-tech/sholawat-json/sholawat/diba/nu_online/fasl/20.json
{
    "number": 20,
    "source": "nu-online",
    "name": "",
    "latin": "Tsumma a‘radla…",
    "sections": {
        "1": {
            "name": "",
            "type": "rawi",
            "text": {
                "1": {
                    "arabic": "ثُمَّ أَعْرَضَ عَنْهُ مَرَاضِعُ الْإِنْسِ لِمَا سَبَقَ فِيْ طَيِّ الْغَيْبِ. مِنَ السَّعَادَةِ لِحَلِيْمَةَ بِنْتِ أَبِيْ ذُؤَيْبٍ. فَلَمَّا وَقَعَ نَظَرُهَا عَلَيْهِ. بَادَرَتْ مُسْــرِعَةً إِلَيْهِ. وَوَضَعَتْهُ فِيْ حِجْرِهَا. وَضَمَّتْهُ إِلَى صَدْرِهَا. فَهَشَّ لَهَا مُتَبَسِّمًا. فَخَرَجَ مِنْ ثَغْرِهٖ نُوْرٌ لَّحِقَ بِالسَّمَآ. فَحَمَلَتْهُ إِلَى رَحْلِهَا. وَارْتَحَلَتْ بِهٖ إِلَى أَهْلِهَا. فَلَمَّا وَصَلَتْ بِهِ إِلَى مُقَامِهَا. عَايَنَتْ بَرَكَتُهٗ عَلَى أَغْنَامِهَا. وَكَانَتْ كُلَّ يَوْمٍ تَرٰى مِنْهُ بُرْهَانًا. وَتَرْفَعُ لَهٗ قَدْرًا وَّشَانًا. حَتَّى انْدَرَجَ فِيْ حُلَّةِ اللُّطْفِ وَالْأَمَانِ. وَدَخَلَ بَيْنَ إِخْوَتِهٖ مَعَ الصِّبْيَانِ",
                    "latin": "Tsumma a‘radla ‘anhu marâdli‘ul-insi limâ sabaqa fî thayyil-ghaibi, minas-sa‘âdati liḫalîmata binti abî dzu’aibin, falammâ waqa’a nadharuhâ ‘alaihi, bâdarat musri’atan ilaihi, wa wadla’athu fî ḫijrihâ, wa dlammathu ilâ shadrihâ, fahasysya lahâ mutabassiman, fakharaja min tsaghrihi nûrun laḫiq bis-samâ, faḫamalathu ilâ raḫlihâ, wartahâlat biḫî ilâ ahlihâ, falammâ washalat bihi ilâ muqâmihâ, ‘âyanat barakatuhu ‘alâ aghnamihâ, wa kânat kulla yaumin tarâ minhu burhânan, wa tartafa’u lahu qadran wa syânan, ḫattân-daraja fî ḫullatil-luthfi wal-amâni, wa dakhala baina ikhwâtihî ma’ash-shibyâni."
                }
            }
        },
        "2": {
            "name": "",
            "type": "closing",
            "text": {
                "1": {
                    "arabic": "اَللّٰهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَيْهِ",
                    "latin": "Allâhumma shalli wa sallim wa bârik 'alaihi wa 'alâ âlihi"
                }
            }
        }
    },
    "translations": {
        "id": {
            "name": "",
            "sections": {
                "1": {
                    "text": {
                        "1": "Kemudian berpalinglah para wanita yang biasa menyusui bayi-bayi karena suratan takdir memang telah menentukan. Kebahagiaan bagi Halimah binti Abi Dzuaib. Tatkala pandangan Halimah tertuju kepada Nabi, segera saja ia meraih bayi itu, meletakkan ke pangkuannya, dan mendekapkan ke dadanya. Sang jabang bayi menampakkan kegembiraan dan senyuman kepadanya. Lalu dari gigi depannya cahaya memancar hingga menembus langit. Kemudian Nabi pun dibawa Halimah menuju tunggangannya, lalu mereka berangkat menuju kampung halamannya. Ketika Halimah dan Nabi tiba di tempat, tampaklah keberkahan sang Nabi atas kambing-kambing ternaknya. Dan setiap hari Halimah melihat tanda-tanda yang luar biasa dari diri Nabi, meningkatnya taraf kehidupan dan kedudukan Halimah, sehingga Nabi pun semakin mendapat kasih sayang dan perlindungannya. serta dapat bergaul bebas dengan anak-anak asuhnya."
                    }
                },
                "2": {
                    "text": {
                        "1": "Ya Allah, limpahkan rahmat, kesalamatan, serta keberkahan kepada Nabi Muhammad beserta keluarga beliau"
                    }
                }
            }
        }
    },
    "last_updated": "2024-12-14"
}
